# coding:utf-8

import pymysql

# 定义一个函数，用来创建连接数据库
def mysql_db():
    con = pymysql.connect(
        host='192.168.7.43',
        port=2023,
        database='my_database',
        charset='utf8',
        user='root',
        password='123456'
    )
    try:
        with con.cursor() as cursor:
            # 一、查询
            # sql = "select * from phone_info;"
            # sql ="insert into phone_info(id, phone_mobile, phone_name)value(1,'123456','vivo Y80');"
            # res = [{"model": "BKL-L09", "name": "HONORView10DualSIM"},
            #        {"model": "LIO-AN00m", "name": "HUAWEIMate30EPro5G全网通版"},
            #        {"model": "OCE-AN50", "name": "HUAWEIMate40E5G全网通版"},
            #        {"model": "OCE-AL50", "name": "HUAWEIMate40E4G全网通版"},
            #        {"model": "TET-AN50", "name": "HUAWEIMateX2典藏版5G全网通版"},
            #        {"model": "TET-AL00", "name": "HUAWEIMateX24G全网通版"},
            #        {"model": "CLT-AL00l", "name": "HUAWEIP20Pro真皮限量版全网通版"},
            #        {"model": "ANA-AL00", "name": "HUAWEIP404G全网通版"}, {"model": "ABR-AL00", "name": "HUAWEIP504G全网通版"},
            #        {"model": "GLK-LX1U", "name": "HUAWEInova5i联通定制版"},
            #        {"model": "CDL-AN50", "name": "HUAWEInova7SE5G乐活版全网通版"},
            #        {"model": "BRQ-AL00", "name": "HUAWEInova8Pro4G全网通版"},
            #        {"model": "NAM-AL00", "name": "HUAWEInova94G全网通版"}, {"model": "DUB-TL00a", "name": "华为畅享9移动4G+顶配版"},
            #        {"model": "AQM-TL00", "name": "华为畅享10S移动4G+版"}, {"model": "DVC-TN20", "name": "华为畅享20Pro5G移动定制版"},
            #        {"model": "WKG-TN00", "name": "华为畅享205G移动定制版"}, {"model": "PPA-AL20", "name": "华为畅享20SE全网通版"},
            #        {"model": "MLD-AL10", "name": "华为畅享20e全网通版(HelioP35)"},
            #        {"model": "PLE-703L", "name": "华为揽阅M2青春版7.0英寸全网通版"},
            #        {"model": "FDR-A03L", "name": "华为揽阅M2青春版10.1英寸LTE版"}, {"model": "BTV-DL09", "name": "华为平板M3LTE版"},
            #        {"model": "CPN-AL00", "name": "华为平板M3青春版8.0英寸全网通版"},
            #        {"model": "BAH-W09", "name": "华为平板M3青春版10.1英寸Wi-Fi版"},
            #        {"model": "BAH-AL00", "name": "华为平板M3青春版10.1英寸全网通版"},
            #        {"model": "SHT-W09", "name": "华为平板M58.4英寸Wi-Fi版"}, {"model": "SHT-AL09", "name": "华为平板M58.4英寸全网通版"},
            #        {"model": "CMR-W09", "name": "华为平板M510.8英寸Wi-Fi版"},
            #        {"model": "CMR-AL09", "name": "华为平板M510.8英寸全网通版"}, {"model": "CMR-AL19", "name": "华为平板M5Pro全网通版"},
            #        {"model": "BAH2-W09", "name": "华为平板M5青春版10.1英寸Wi-Fi版"},
            #        {"model": "BAH2-AL10", "name": "华为平板M5青春版10.1英寸全网通版"},
            #        {"model": "VRD-W09", "name": "华为平板M68.4英寸Wi-Fi版"}, {"model": "VRD-AL09", "name": "华为平板M68.4英寸全网通版"},
            #        {"model": "VRD-W10", "name": "华为平板M6高能版8.4英寸Wi-Fi版"},
            #        {"model": "VRD-AL10", "name": "华为平板M6高能版8.4英寸全网通版"},
            #        {"model": "SCM-W09", "name": "华为平板M610.8英寸Wi-Fi版"},
            #        {"model": "SCM-AL09", "name": "华为平板M610.8英寸全网通版"},
            #        {"model": "MRX-AL09", "name": "HUAWEIMatePadPro10.8英寸全网通版(6GB+128GB/8GB+256GB)"},
            #        {"model": "MRX-AL19", "name": "HUAWEIMatePadPro10.8英寸全网通版(8GB+512GB)"},
            #        {"model": "MRX-AN19", "name": "HUAWEIMatePadPro10.8英寸5G全网通版"},
            #        {"model": "WGR-AN19", "name": "HUAWEIMatePadPro12.6英寸全网通版(麒麟9000)"},
            #        {"model": "BAH3-AL00", "name": "HUAWEIMatePad10.4英寸全网通版(麒麟810)"},
            #        {"model": "SCMR-W09", "name": "HUAWEIMatePad10.8英寸Wi-Fi版"},
            #        {"model": "DBY-W09", "name": "HUAWEIMatePad11英寸Wi-Fi版"},
            #        {"model": "AGS2-AL00", "name": "华为畅享平板10.1英寸全网通版"},
            #        {"model": "AGS3-W00D", "name": "华为畅享平板210.1英寸Wi-Fi版(4GB+64GB)"},
            #        {"model": "AGS3-W00E", "name": "华为畅享平板210.1英寸Wi-Fi版(4GB+128GB)"},
            #        {"model": "BZK-W00", "name": "华为平板C3(华为平板T3行业专享版)8英寸Wi-Fi版"},
            #        {"model": "BZA-L00", "name": "华为平板C3(华为平板T3行业专享版)9.6英寸LTE版"},
            #        {"model": "MON-AL19", "name": "华为平板C58英寸全网通版"}, {"model": "BZT-W09", "name": "华为平板C510.1英寸Wi-Fi版"},
            #        {"model": "BZT-AL00", "name": "华为平板C510.1英寸全网通标配版"},
            #        {"model": "BZW-AL10", "name": "华为平板C58英寸2020款全网通版(4GB+64GB)"},
            #        {"model": "8681-M02", "name": "360手机奇酷青春版双网通版"}, {"model": "MHA-L29", "name": "HUAWEIMate9DualSIM"},
            #        {"model": "LON-L29", "name": "PORSCHEDESIGNHUAWEIMate9DualSIM"},
            #        {"model": "BLA-A09", "name": "PORSCHEDESIGNHUAWEIMate10(UnitedStates)"},
            #        {"model": "BND-L34", "name": "HUAWEIMateSE(UnitedStates)"},
            #        {"model": "NEO-L29", "name": "PORSCHEDESIGNHUAWEIMateRSDualSIM"},
            #        {"model": "HMA-L09", "name": "HUAWEIMate20SingleSIM"},
            #        {"model": "HMA-L29", "name": "HUAWEIMate20DualSIM"},
            #        {"model": "LYA-L29", "name": "PORSCHEDESIGNHUAWEIMate20RSDualSIM"},
            #        {"model": "EVR-L29", "name": "HUAWEIMate20XDualSIM"},
            #        {"model": "TAS-L29", "name": "HUAWEIMate30DualSIM"},
            #        {"model": "NOH-NX9", "name": "HUAWEIMate40Pro5GDualSIM"},
            #        {"model": "EVA-L09", "name": "HUAWEIP9SingleSIM"},
            #        {"model": "VTR-L09", "name": "HUAWEIP10SingleSIM"},
            #        {"model": "VKY-L09", "name": "HUAWEIP10PlusSingleSIM"},
            #        {"model": "VKY-L29", "name": "HUAWEIP10PlusDualSIM"},
            #        {"model": "EML-L09", "name": "HUAWEIP20SingleSIM"},
            #        {"model": "ELE-L09", "name": "HUAWEIP30SingleSIM"}, {"model": "ELE-L29", "name": "HUAWEIP30DualSIM"},
            #        {"model": "VOG-L09", "name": "HUAWEIP30ProSingleSIM"},
            #        {"model": "VOG-L29", "name": "HUAWEIP30ProDualSIM"},
            #        {"model": "ELS-NX9", "name": "HUAWEIP40ProDualSIM"},
            #        {"model": "JNY-LX1", "name": "HUAWEInova7iDualSIM"},
            #        {"model": "JNY-LX2", "name": "HUAWEIP40liteSingleSIM"},
            #        {"model": "INE-LX1", "name": "HUAWEIPsmart+"}, {"model": "STK-L21", "name": "HUAWEIY9sSingleSIM"},
            #        {"model": "PPA-LX2", "name": "HUAWEIPsmart2021DualSIM"},
            #        {"model": "LDN-LX2", "name": "HUAWEInova2lite"}, {"model": "VCE-L22", "name": "HUAWEInova4"},
            #        {"model": "YAL-L21", "name": "HUAWEInova5T"}, {"model": "YAL-L41", "name": "HUAWEInova5TPro"},
            #        {"model": "DRA-LX9", "name": "HUAWEIY5pDualSIM"},
            #        {"model": "LDN-L21", "name": "HUAWEIY7Prime2018DualSIM"},
            #        {"model": "AQM-LX1", "name": "HUAWEIY8pDualSIM"}, {"model": "M973Q", "name": "魅族16sPro公开版"},
            #        {"model": "XT1965-6", "name": "motorolag7plus"}, {"model": "XT1970-5", "name": "motorolap50"},
            #        {"model": "XT2071-4", "name": "motorolarazr5G"}, {"model": "XT2125-4", "name": "motorolaedges"},
            #        {"model": "XT2143-1", "name": "motorolaedge轻奢版"}, {"model": "XT2153-1", "name": "motorolaedgespro"},
            #        {"model": "XT2137-2", "name": "motorolag50"}, {"model": "TA-1094", "name": "Nokia9PureView"},
            #        {"model": "NX507J", "name": "nubiaZ7mini全网通版"}, {"model": "NX627J", "name": "nubiaZ20"},
            #        {"model": "NX659J", "name": "红魔5S"}, {"model": "NX669J", "name": "腾讯红魔游戏手机6"},
            #        {"model": "NX666J", "name": "腾讯红魔游戏手机6R"}, {"model": "NX651J", "name": "nubiaPlay"},
            #        {"model": "HD1925", "name": "OnePlus7TPro5GT-Mobile版/OnePlusConceptOne"},
            #        {"model": "KB2000", "name": "OnePlus8T全网通版"}, {"model": "LE2100", "name": "OnePlus9R全网通版"},
            #        {"model": "LE2110", "name": "OnePlus9全网通版"}, {"model": "MT2110", "name": "OnePlus9RT全网通版"},
            #        {"model": "BE2029", "name": "OnePlusNordN10国际版"}, {"model": "PEDM00", "name": "OPPOFindX3全网通版"},
            #        {"model": "PEEM00", "name": "OPPOFindX3Pro全网通版"}, {"model": "PEGT00", "name": "OPPOReno5移动版"},
            #        {"model": "PEGT10", "name": "OPPOReno5K移动版"}, {"model": "PDRM00", "name": "OPPOReno5Pro+全网通版"},
            #        {"model": "PEQM00", "name": "OPPOReno6全网通版"}, {"model": "PFCM00", "name": "OPPOReno7SE全网通版"},
            #        {"model": "PBBT00", "name": "OPPOA7x移动版"}, {"model": "PCDM00", "name": "OPPOA7n全网通版"},
            #        {"model": "PCDT00", "name": "OPPOA7n移动版"}, {"model": "PEFM00", "name": "OPPOA35全网通版"},
            #        {"model": "PDAT10", "name": "OPPOA52移动版"}, {"model": "PECT30", "name": "OPPOA53(2020)移动版"},
            #        {"model": "PFVM10", "name": "OPPOA56全网通版"}, {"model": "PDYM10", "name": "OPPOA72n全网通版"},
            #        {"model": "PEHM00", "name": "OPPOA93全网通版"}, {"model": "PEHT00", "name": "OPPOA93移动版"},
            #        {"model": "PFGM00", "name": "OPPOA93s全网通版"}, {"model": "PELM00", "name": "OPPOA95全网通版"},
            #        {"model": "PERM00", "name": "OPPOK7x全网通版"}, {"model": "PERM10", "name": "OPPOK9s全网通版"},
            #        {"model": "PEYM00", "name": "OPPOK9Pro全网通版"}, {"model": "CPH2145", "name": "OPPOReno55G"},
            #        {"model": "CPH1979", "name": "OPPORenoZ"}, {"model": "CPH2159", "name": "OPPOReno5"},
            #        {"model": "CPH2201", "name": "OPPOReno5Pro"},
            #        {"model": "CPH2095", "name": "OPPOF17"}, {"model": "CPH1879", "name": "OPPOR17"},
            #        {"model": "CPH1877", "name": "OPPOR17Pro"}, {"model": "CPH1903", "name": "OPPOAX7"},
            #        {"model": "CPH2161", "name": "OPPOA735G"}, {"model": "CPH2211", "name": "OPPOA945G"},
            #        {"model": "RMX2025", "name": "真我X505G移动版"}, {"model": "RMX2072", "name": "真我X50Pro玩家版"},
            #        {"model": "RMX2052", "name": "真我X50t5G"}, {"model": "RMX3115", "name": "真我X7Pro至尊版5G全网通版"},
            #        {"model": "RMX2201", "name": "真我V35G运营商定制版"}, {"model": "RMX2112", "name": "真我V55G运营商定制版"},
            #        {"model": "RMX3122", "name": "真我V115G运营商定制版"}, {"model": "RMX3041", "name": "真我V135G全网通版"},
            #        {"model": "RMX3092", "name": "真我V155G全网通版"},
            #        {"model": "RMX2173", "name": "真我Q2Pro5G"}, {"model": "RMX3161", "name": "真我Q35G"},
            #        {"model": "RMX2205", "name": "真我Q3Pro5G"}, {"model": "RMX3142", "name": "真我Q3Pro狂欢版5G"},
            #        {"model": "RMX3042", "name": "真我Q3i5G"}, {"model": "RMX3461", "name": "真我Q3s5G"},
            #        {"model": "RMX2202", "name": "真我GT5G"}, {"model": "RMX3031", "name": "真我GTNeo5G"},
            #        {"model": "RMX3350", "name": "真我GTNeo闪速版5G"}, {"model": "RMX3361", "name": "真我GT大师版5G"},
            #        {"model": "RMX3366", "name": "真我GT大师探索版5G"}, {"model": "RMX3370", "name": "真我GTNeo25G"},
            #        {"model": "RMX3357", "name": "真我GTNeo2T5G"}, {"model": "RMX3085", "name": "realme8"},
            #        {"model": "GT-I9507V", "name": "GalaxyS4联通4G定制版"}, {"model": "SM-G7810", "name": "GalaxyS20FE5G"},
            #        {"model": "SM-G9910", "name": "GalaxyS215G"}, {"model": "SM-G9960", "name": "GalaxyS21+5G"},
            #        {"model": "SM-G9980", "name": "GalaxyS21Ultra5G"}, {"model": "SM-F9160", "name": "GalaxyZFold25G"},
            #        {"model": "SM-F9260", "name": "GalaxyZFold35G"}, {"model": "SM-F7070", "name": "GalaxyZFlip5G"},
            #        {"model": "SM-F7110", "name": "GalaxyZFlip35G"},
            #          {"model": "V2111A", "name": "vivoy53s"},
            #        {"model": "PEGM00", "name": "opporeno5"}, {"model": "M2012K11C", "name": "红米k40pro"},
            #        {"model": "PCHM00", "name": "oppok9pro"}, {"model": "LIO-L29", "name": "华为mate30pro"},
            #        {"model": "AGS3-AL00", "name": "华为畅享平板2"}, {"model": "conquest-S16", "name": "征服S16"},
            #        {"model": "INE-LX2", "name": "华为nova3i"}, {"model": "MRX-W09", "name": "华为matepadpro"},
            #        {"model": "SM-G991U", "name": "SamsungGalaxyS21"},
            #        {"model": "SM-A207F", "name": "SamsungGalaxyA20s"}, {"model": "21091116AC", "name": "红米note115G"},
            #         {"model": "M2007J20CG", "name": "小米POCOX3"},
            #        {"model": "M12pro", "name": "金立M12pro"}, {"model": "SM-G981U", "name": "SamsungGalaxyS205G"},
            #        {"model": "SM-G998B", "name": "SamsungGalaxyS21Ultra5G"}, {"model": "CPH1727", "name": "OPPOF5pro"},
            #        {"model": "K30", "name": "红米K30"}, {"model": "4A", "name": "荣耀4A"},
            #        {"model": "MiNote10Lite", "name": "小米note10Lite"}, {"model": "ATMANX20(X9S)", "name": "创星X20"},
            #        {"model": "A1Q", "name": "AGMA1Q"}, {"model": "ZTEA2022H", "name": "中兴Axon30Pro"},
            #        {"model": "FRD-AL00", "name": "华为荣耀8"}, {"model": "LenovoTB-8704N", "name": "联想Tab4/Plus"},
            #        {"model": "PDBM00", "name": "oppoA8"}, {"model": "MX20Plus", "name": "米语mx20plus"},
            #        {"model": "R11", "name": "oppoR11"}, {"model": "V2057A", "name": "VIVOY52s"},
            #        {"model": "V2020CA", "name": "VIVOS7"}, {"model": "BTV-W09", "name": "华为M3平板"},
            #        {"model": "TYH611M", "name": "华为麦芒10se"}, {"model": "JDN-AL00", "name": "华为荣耀平板2"},
            #        {"model": "M20", "name": "SamsungGalaxyM20"}, {"model": "VTR-L29", "name": "华为P10"},
            #        {"model": "V2156A", "name": "vivoY76s"}, {"model": "ANA-NX9", "name": "华为P40"},
            #        {"model": "JDN-W09", "name": "华为荣耀平板2"}, {"model": "TET-AN10", "name": "华为荣耀X10"},
            #        {"model": "LM-Q815L", "name": "LGQ8"}, {"model": "ZTEA2020N2Pro", "name": "中兴天机10pro"},
            #        {"model": "CDY-NX9A", "name": "华为P40lite5G"}, {"model": "DT1901A", "name": "锤子坚果pro3"},
            #        {"model": "KONKAD18", "name": "康佳D18"}, {"model": "ZTE8010", "name": "中兴ZTE8010"},
            #        {"model": "V2022", "name": "中兴BladeV2022"}, {"model": "LYA-L09", "name": "华为Mate20Pro"},
            #        {"model": "MuMu", "name": "mumu安卓模拟器"}, {"model": "LenovoTB-8705F", "name": "联想TabM8"},
            #        {"model": "SM-A326W", "name": "SamsungGalaxyA325G"},
            #        {"model": "i12ProMax", "name": "iPhone12ProMax"},
            #        {"model": "SM-G9287", "name": "SamsungGlaxyS6edgePlus"}, {"model": "CPH1901", "name": "oppoA7"},
            #        {"model": "SM-A217F", "name": "SamsungGalaxyA21s"}, {"model": "LG-US998", "name": "LGV30"},
            #        {"model": "OPPOA73t", "name": "OPPOA73t"}, {"model": "CPH1911", "name": "oppoF11"},
            #        {"model": "koobeeS106", "name": "酷比S106m"}, {"model": "ZTEA2022P", "name": "中兴Axon30Ultra"},
            #        {"model": "x600", "name": "SamsungX600"}, {"model": "NokiaX20", "name": "诺基亚X20"},
            #        {"model": "M6", "name": "魅族魅蓝M6"}, {"model": "VIE-L29", "name": "华为P9plus海外版"},
            #        {"model": "XQ-AU52", "name": "索尼XQ-AU52"}, {"model": "11promax", "name": "iPhone11promax"},
            #        {"model": "T1", "name": "vivoT1"},
            #        {"model": "V2056A", "name": "VivoX60Pro+"}, {"model": "V2099A", "name": "VivoY302021"},
            #        {"model": "SM-J530L", "name": "SamsungGalaxyJ5"}, {"model": "V2069A", "name": "VIVOY53S"},
            #        {"model": "V2059A", "name": "vivoX60曲屏"}, {"model": "GLK-TL00", "name": "HUAWEInova5i"},
            #        {"model": "MED-LX9", "name": "HuaweiY6P"}, {"model": "ONEPLUSA6013", "name": "OnePlus6T"},
            #        {"model": "JDN2-W09", "name": "华为M5"}, {"model": "21091116UC", "name": "红米Note11Pro+"},
            #        {"model": "P40Pro", "name": "华为P40Pro"}, {"model": "iPlay_20", "name": "酷比魔方iPlay20"},
            #        {"model": "HL2001", "name": "九爱V1S"}, {"model": "G0515D", "name": "格力1W"},
            #        {"model": "CPH1907", "name": "OPPO-Reno2"}, {"model": "SM-T295C", "name": "SamsungGalaxyTabA"},
            #        {"model": "XHF-M001", "name": "小黄蜂XHF-M001"}, {"model": "SM-G960N", "name": "SamsungS9"},
            #        {"model": "CPH2219", "name": "OppoF19"}, {"model": "E910", "name": "海信E910"},
            #        {"model": "BOS-A0", "name": "酷派BOS-A0"}, {"model": "P027", "name": "华硕P027"},
            #        {"model": "GIONEEM50Pro", "name": "金立M50Pro"}, {"model": "AGM3-AL09HN", "name": "荣耀(honor)平板电脑平板7"},
            #        {"model": "SM-G960U1", "name": "SamsungGalaxyS9"}, {"model": "VOG-L04", "name": "华为(HUAWEI)P30Pro"},
            #        {"model": "HL3001", "name": "九爱HL3001"}, {"model": "BZT-AL10", "name": "华为C510"},
            #        {"model": "SM-F916N", "name": "SamsungGalaxyFold2"},
            #        {"model": "SHARKMBU-A0", "name": "XiaomiBlackShark3Pro"}, {"model": "vivo1908", "name": "vivoY90"},
            #        {"model": "S410J", "name": "Philips/飛利浦M9S"}, {"model": "FZ-S05", "name": "EXSECURTEL手机FZ-S05"},
            #        {"model": "Q18", "name": "万利达q18"}, {"model": "GIONEEF6L", "name": "金立F6L"},
            #        {"model": "Nokia8Sirocco", "name": "诺基亚8Sirocco"},
            #        {"model": "JD-PLUS(移动版)", "name": "小辣椒红辣椒JD-Plus"},
            #        {"model": "SM-T385C", "name": "SamsungGalaxyTabA"}, {"model": "PDSM00", "name": "OPPOReno5Pro"},
            #        {"model": "TFY-AN00", "name": "华为荣耀X30i"}, {"model": "TYH211U", "name": "沃尔驴天翼一号"},
            #        {"model": "VP001", "name": "U-Magic优畅享20Plus"}, {"model": "SM-A5260", "name": "SamsungA52"},
            #        {"model": "RMX2117", "name": "OPPORealmeQ25G"},
            #        {"model": "SM-A5160", "name": "SamsungGalaxyA515G"},
            #        {"model": "EML-L29", "name": "HuaweiP20EML-L29"}, {"model": "ZUKZ1", "name": "联想ZUKZ1"},
            #        {"model": "AGM3-W09HN", "name": "荣耀平板7"}, {"model": "R40Pro", "name": "小辣椒R40pro"},
            #        {"model": "CPH1723", "name": "OPPOF5"}, {"model": "NokiaC3", "name": "NokiaC3"},
            #        {"model": "HUAWEIMLA-L12", "name": "华为Novaplus"}, {"model": "LE2120", "name": "一加9pro"},
            #        {"model": "CPH1937", "name": "OppoA92020"},
            #        {"model": "angelcare_F20", "name": "中兴angelcare守护宝F20Pro"}, {"model": "GIONEEF40", "name": "金立F40"},
            #        {"model": "G1701", "name": "吉客猫glocalmeg1701"}, {"model": "LenovoTB-J607F", "name": "小新PadPlus"},
            #        {"model": "CMCM5S", "name": "厘米cm5s"}, {"model": "SM-A2070", "name": "SAMSUNG三星GalaxyA20s"},
            #        {"model": "DN2103", "name": "OPPOOnePlus"},
            #        {"model": "V2045A", "name": "VivoX60"},
            #        {"model": "Mi9SE", "name": "小米9SE"}, {"model": "WGR-W09", "name": "HUAWEIMatePadPro平板"},
            #        {"model": "SM-G610L", "name": "GALAXYOn7"}, {"model": "XQ-AS72", "name": "xperia5ii"},
            #        {"model": "HUAWEIVNS-L31", "name": "HUAWEIP9LITE"}, {"model": "ChanghongR9", "name": "长虹R9"},
            #        {"model": "TAH-N29m", "name": "华为mateXs"}, {"model": "V2046A", "name": "vivo-X60"},
            #        {"model": "V2121A", "name": "vivoS10"}, {"model": "V2048A", "name": "vivos9e"},
            #        {"model": "CHL-AL00", "name": "荣耀Play5T"},
            #        {"model": "JAD-AL50", "name": "华为P50Pro"}, {"model": "NAT-TN70", "name": "鼎桥NAT-TN70"},
            #        {"model": "FDR-A01w", "name": "华为揽阅M2青春版"}, {"model": "Joyar_62_64", "name": "3GPAD"},
            #        {"model": "V2023EA", "name": "vivoX70"}, {"model": "M40SE(M5T3)", "name": "台电M40SE"},
            #        {"model": "MIPAD3", "name": "小米平板3"}, {"model": "M1", "name": "小米M1"},
            #        {"model": "SM-A530N", "name": "三星GalaxyA8"}, {"model": "MiMIX35G", "name": "小米MIX35G"},
            #         {"model": "BAH3-AN10", "name": "华为MatePad5G"},
            #        {"model": "LDOX-2121", "name": "天语MT40"}, {"model": "SM-A730F", "name": "三星A730F"},
            #        {"model": "SM-G960F", "name": "SamsungGalaxyS9"}, {"model": "S27MIX", "name": "欧加S27MIX"},
            #        {"model": "HTC_VR_V1", "name": "HtcViveVR"}, {"model": "GM1913", "name": "ONEPLUS7PRO"},
            #        {"model": "M10", "name": "小米10"}, {"model": "vivox6a", "name": "vivox6a"},
            #        {"model": "WII-AL00", "name": "华为畅享20e"}, {"model": "oppoa83", "name": "oppoa83"},
            #        {"model": "TablePC", "name": "Table平板"}, {"model": "CPH2061", "name": "OPPOA52"},
            #        {"model": "LenovoL70081", "name": "LENOVOL70081整机拯救者2"},
            #        {"model": "i7S(YP7S)", "name": "誉品（YEPEN）i7s"},
            #        {"model": "HTCDesire10pro", "name": "HTCDesire10pro"}, {"model": "PEGM10", "name": "OPPOReno5K"},
            #        {"model": "V2133A", "name": "VIVOX70"}, {"model": "PENM00", "name": "OPPOReno6"},
            #        {"model": "V19", "name": "vivoV19"},
            #        {"model": "TYH201H", "name": "天翼1号"}, {"model": "V2145A", "name": "VIVOX70"},
            #        {"model": "MIPAD4", "name": "小米平板4"}, {"model": "RNE-L22", "name": "华为荣耀9i"},
            #        {"model": "PFJM10", "name": "OPPOReno7"}, {"model": "HLK-AL00a", "name": "荣耀9X"},
            #        {"model": "X50Pro", "name": "vivoX50Pro5G版"}, {"model": "DT2002C", "name": "锤子科技坚果R2"},
            #        {"model": "M2102K1AC", "name": "小米11Pro"}, {"model": "SUGARS30", "name": "SUGARS30"},
            #        {"model": "SM-G991N", "name": "三星GalaxyS21"}, {"model": "SOAPR11", "name": "SUGARSOAPR11lite"},
            #        {"model": "T1-823L", "name": "华为T1-823L平板"}, {"model": "BDS2Plus", "name": "北斗复兴BDS2"},
            #        {"model": "MOA-AL20", "name": "华为荣耀畅玩9A"}, {"model": "V30", "name": "荣耀V30"},
            #        {"model": "ivviP60", "name": "依偎（ivvi）P60"}, {"model": "V2026", "name": "vivoY12s"},
            #        {"model": "X12pro", "name": "小辣椒X12pro"},
            #        {"model": "V2002A", "name": "vivoY70s"}, {"model": "V1818A", "name": "vivoY93"},
            #        {"model": "vivoX6D", "name": "vivoX6D"}, {"model": "V1901A", "name": "vivoY3"},
            #        {"model": "SEA-AL10", "name": "HUAWEInova5pro"}, {"model": "JKM-AL00a", "name": "HUAWEI畅享9Plus"},
            #        {"model": "DUB-TL0", "name": "HUAWEI畅享9"}, {"model": "DUB-AL20", "name": "HUAWEI荣耀8x"},
            #        {"model": "PACT00", "name": "OPPOr15"}, {"model": "PCAM10", "name": "OPPOA9"},
            #        {"model": "PADM00", "name": "OPPOA3"}, {"model": "PBBM30", "name": "OPPOA5"},
            #        {"model": "RedmiK20Pro", "name": "RedmiK20Pro"}, {"model": "PCAM00", "name": "OPPOReno"},
            #        {"model": "JSN-AL00a", "name": "华为荣耀8X"}, {"model": "V1930A", "name": "vivo Y3"},
            #        {"model": "PAAM00", "name": "oppo R15"}, {"model": "ART-AL00x", "name": "华为畅享10"},
            #        {"model": "DUB-AL00", "name": "华为畅享9"}, {"model": "ASK-AL00x", "name": "荣耀Play3"},
            #        {"model": "LRA-AL00", "name": "华为荣耀20"}, {"model": "STK-AL00", "name": "畅享10Plus"},
            #        {"model": "BND-AL10", "name": "荣耀畅玩7X"}, {"model": "ELE-AL00", "name": "华为p30"},
            #        {"model": "V1934A", "name": "vivoy5s"}, {"model": "FIG-AL10", "name": "华为畅享7S"},
            #        {"model": "DVC-AN20", "name": "手机畅享20Pro"}, {"model": "V1911A", "name": "vivoZ5X"},
            #        {"model": "V1732A", "name": "vivoY81S"}, {"model": "V1965A", "name": "vivoY50"},
            #
            #        {"model": "V1813A", "name": "vivoY97"}, {"model": "PEMM20", "name": "OPPOA55"},
            #
            #        {"model": "PBAT00", "name": "oppoA5"}, {"model": "PBBM00", "name": "A7x"},
            #
            #        {"model": "TEL-TN00", "name": "荣耀10x"}, {"model": "CDY-AN00", "name": "nova7 SE"},
            #        {"model": "荣耀Play4T", "name": "荣耀Play4T"}, {"model": "HMA-AL00", "name": "HUAWEI mate20"},
            #        {"model": "MED-AL00", "name": "畅享 10e"}]

            res = [{"packinfo": "中台_计步_V1.0.4_兜底", "adinfo": "splash,game_awaken,newfriend_video,newfriend_msg,5yuan_video,5yuan_msg,3mao_msg,8888_first_video,8888_second_video,8888_third_video,load_msg,double_mfzs,extra_mfzs,tx_video,wmtx_video,switch_plaque,auto_video,txym_msg,djhb_video,lqbx_video,lqhb_video,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_计步_V1.0.4_HW", "adinfo": "splash,game_awaken,newfriend_video,newfriend_msg,5yuan_video,5yuan_msg,3mao_msg,8888_first_video,8888_second_video,8888_third_video,load_msg,double_mfzs,extra_mfzs,tx_video,wmtx_video,switch_plaque,auto_video,txym_msg,djhb_video,lqbx_video,lqhb_video,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_计步_V1.0.4_OP", "adinfo": "splash,game_awaken,newfriend_video,newfriend_msg,5yuan_video,5yuan_msg,3mao_msg,8888_first_video,8888_second_video,8888_third_video,load_msg,double_mfzs,extra_mfzs,tx_video,wmtx_video,switch_plaque,auto_video,txym_msg,djhb_video,lqbx_video,lqhb_video,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_计步_V1.0.4_VI", "adinfo": "splash,game_awaken,newfriend_video,newfriend_msg,5yuan_video,5yuan_msg,3mao_msg,8888_first_video,8888_second_video,8888_third_video,load_msg,double_mfzs,extra_mfzs,tx_video,wmtx_video,switch_plaque,auto_video,txym_msg,djhb_video,lqbx_video,lqhb_video,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_计步_V1.0.4_HW_【合规调整+D】", "adinfo": "splash,game_awaken,newfriend_video,newfriend_msg,5yuan_video,5yuan_msg,3mao_msg,8888_first_video,8888_second_video,8888_third_video,load_msg,double_mfzs,extra_mfzs,tx_video,wmtx_video,switch_plaque,auto_video,txym_msg,djhb_video,lqbx_video,lqhb_video,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "GATE_计步_V1.0.0", "adinfo": "splash,game_awaken,newfriend_video,newfriend_msg,5yuan_video,5yuan_msg,3mao_msg,8888_first_video,8888_second_video,8888_third_video,load_msg,double_mfzs,extra_mfzs,tx_video,wmtx_video,switch_plaque,auto_video,txym_msg,djhb_video,lqbx_video,lqhb_video,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "GATE_计步_V1.0.7.3_datax", "adinfo": "splash,game_awaken,newfriend_video,newfriend_msg,5yuan_video,5yuan_msg,3mao_msg,8888_first_video,8888_second_video,8888_third_video,load_msg,double_mfzs,extra_mfzs,tx_video,wmtx_video,switch_plaque,auto_video,txym_msg,djhb_video,lqbx_video,lqhb_video,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_计步_V1.0.4_VI【弹出优化】", "adinfo": "splash,game_awaken,newfriend_video,newfriend_msg,5yuan_video,5yuan_msg,3mao_msg,8888_first_video,8888_second_video,8888_third_video,load_msg,double_mfzs,extra_mfzs,tx_video,wmtx_video,switch_plaque,auto_video,txym_msg,djhb_video,lqbx_video,lqhb_video,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "GATE_清理、wifi、省电_V1.0.0", "adinfo": "splash,game_awaken,recommend_msg,clean_landing,level_win,scan_plaque,htend_plaque,dsshome_msg,adjust_video,jkzs_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "GATE_wifi_【穿山甲平台广告合规化】", "adinfo": "scratch_video,make_video,bottom_msg,switch_plaque"}, {"packinfo": "中台_清理、wifi、省电_V2.0.2_兜底", "adinfo": "splash,game_awaken,recommend_msg,clean_landing,level_win,scan_plaque,htend_plaque,dsshome_msg,adjust_video,jkzs_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_清理、wifi、省电_V2.0.2_HW", "adinfo": "splash,game_awaken,recommend_msg,clean_landing,level_win,scan_plaque,htend_plaque,dsshome_msg,adjust_video,jkzs_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_清理、wifi、省电_V2.0.2_OP", "adinfo": "splash,game_awaken,recommend_msg,clean_landing,level_win,scan_plaque,htend_plaque,dsshome_msg,adjust_video,jkzs_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_清理、wifi、省电_V2.0.2_VI", "adinfo": "splash,game_awaken,recommend_msg,clean_landing,level_win,scan_plaque,htend_plaque,dsshome_msg,adjust_video,jkzs_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_清理、wifi、省电_V2.0.2_【合规调整】HW", "adinfo": "splash,game_awaken,recommend_msg,clean_landing,level_win,scan_plaque,htend_plaque,dsshome_msg,adjust_video,jkzs_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "GATE_大字报_V1.0.0", "adinfo": "splash,game_awaken,adjust_video,exit_msg,leave_splash,zxtc_msg,jkzs_plaque,weather_msg,news_landing,my_msg,lqbx_video,lqhb_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_大字报_V1.0.3_兜底", "adinfo": "splash,game_awaken,adjust_video,exit_msg,leave_splash,zxtc_msg,jkzs_plaque,weather_msg,news_landing,my_msg,lqbx_video,lqhb_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_大字报_V1.0.3_HW", "adinfo": "splash,game_awaken,adjust_video,exit_msg,leave_splash,zxtc_msg,jkzs_plaque,weather_msg,news_landing,my_msg,lqbx_video,lqhb_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_大字报_V1.0.3_OP", "adinfo": "splash,game_awaken,adjust_video,exit_msg,leave_splash,zxtc_msg,jkzs_plaque,weather_msg,news_landing,my_msg,lqbx_video,lqhb_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_大字报_V1.0.3_VI", "adinfo": "splash,game_awaken,adjust_video,exit_msg,leave_splash,zxtc_msg,jkzs_plaque,weather_msg,news_landing,my_msg,lqbx_video,lqhb_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_大字报_V1.0.3_VI【弹出优化】", "adinfo": "splash,game_awaken,adjust_video,exit_msg,leave_splash,zxtc_msg,jkzs_plaque,weather_msg,news_landing,my_msg,lqbx_video,lqhb_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "GATE_充电_V1.0.0", "adinfo": "splash,game_awaken,powersaving_video,speedup_video,care_msg,set_video,switch_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "GATE_充电_【测试】V1.0.1", "adinfo": "splash,game_awaken,powersaving_video,speedup_video,care_msg,set_video,switch_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "GATE_充电_【测试】V1.0.2", "adinfo": "splash,game_awaken,powersaving_video,speedup_video,care_msg,set_video,switch_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "GATE_充电_【穿山甲平台广告合规化】", "adinfo": "powersaving_video,speedup_video,care_msg,set_video,switch_plaque"}, {"packinfo": "中台_充电_V1.0.4_兜底", "adinfo": "splash,game_awaken,powersaving_video,speedup_video,care_msg,set_video,switch_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_充电_V1.0.4_HW", "adinfo": "splash,game_awaken,powersaving_video,speedup_video,care_msg,set_video,switch_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_充电_V1.0.4_OP", "adinfo": "splash,game_awaken,powersaving_video,speedup_video,care_msg,set_video,switch_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_充电_V1.0.4_VI", "adinfo": "splash,game_awaken,powersaving_video,speedup_video,care_msg,set_video,switch_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_充电_V1.0.4_VI【弹出优化】", "adinfo": "splash,game_awaken,powersaving_video,speedup_video,care_msg,set_video,switch_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_充电_V1.0.4_OP【1466插件版1.0.12】", "adinfo": "splash,game_awaken,powersaving_video,speedup_video,care_msg,set_video,switch_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_充电_V1.0.4_【1466】HW", "adinfo": "splash,game_awaken,powersaving_video,speedup_video,care_msg,set_video,switch_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_充电_V1.0.0_【1466】HW-电池好卫士", "adinfo": "splash,game_awaken,powersaving_video,speedup_video,care_msg,set_video,switch_plaque,news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "GATE_天气_V1.0.0", "adinfo": "splash,game_awaken,news_msg,more_video,check_video,jkzs_plaque,news_landing,adjust_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_天气_V1.1.8_兜底", "adinfo": "splash,game_awaken,news_msg,more_video,check_video,jkzs_plaque,news_landing,adjust_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_天气_V1.1.8_HW", "adinfo": "splash,game_awaken,news_msg,more_video,check_video,jkzs_plaque,news_landing,adjust_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_天气_V1.1.8_OP", "adinfo": "splash,game_awaken,news_msg,more_video,check_video,jkzs_plaque,news_landing,adjust_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_天气_V1.1.8_VI", "adinfo": "splash,game_awaken,news_msg,more_video,check_video,jkzs_plaque,news_landing,adjust_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_天气_V1.1.8_VI【弹出优化】", "adinfo": "splash,game_awaken,news_msg,more_video,check_video,jkzs_plaque,news_landing,adjust_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "中台_天气_V1.1.8【1466插件版1.0.12】", "adinfo": "splash,game_awaken,news_msg,more_video,check_video,jkzs_plaque,news_landing,adjust_video,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "shelf_通用_v1.0.0【HW定制化】", "adinfo": "news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "shelf_通用_v1.0.0【HW定制化+带D+1463】", "adinfo": "news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "shelf_通用_v1.0.0【HW定制化+带D+1466+合规调整】", "adinfo": "news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "shelf_通用_v1.0.0【HW定制化+小D】", "adinfo": "news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "shelf_通用_v1.0.0【兜底包】", "adinfo": "news_landing,game_clean,game_video,game_ad,olanding_msg"}, {"packinfo": "GATE_计步_V1.0.7.3", "adinfo": "splash,2_plaque,game_awaken,first_msg,new_first_mix,first_bp_plaque,new_more_mix,tx_button,txbp_plaque,result_msg,sign_video,add_video,wx_video,2_tx_mix,limit_msg,succ_msg,2_queue_mix,2_bp_plaque,shared_ad_video,shared_ad_msg,lottery_plaque,news_landing,adjust_video,game_clean,game_video,game_ad,olanding_msg"}]

            for i in res:
                phonemobile = i['packinfo']
                phonename = i['adinfo']
                sql =f"insert into adinfotable(package_info, ad_name)value('{phonemobile}','{phonename}');"

            # 执行SQL语句
            # 执行后的结果都保存在cursor中
                cursor.execute(sql)

            # 1-从cursor中获取全部数据用fetchall
            # datas = cursor.fetchall()
            # print("获取的数据：\n",datas)

            # 2-从cursor中获取一条数据用fetchall
            # data = cursor.fetchone()
            # print("获取的数据：\n",data)

            # 3-想要从cursor中获取几条数据用fetchmany
            # datas = cursor.fetchmany(3)
            # print("获取的数据：\n", datas)
            # 执行玩SQL语句要提交
                con.commit()
                print("提交成功")

    except Exception as e:
        con.rollback()
        print("数据库异常：\n", e)
    finally:
        # 不管成功还是失败，都要关闭数据库连接
        con.close()


if __name__ == '__main__':
    mysql_db()