# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CombineTestToolsFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1004, 711)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/WindowTitle/WindowIco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {alignment: center;}\n"
"QTabBar::tab{width:200px;}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setStyleSheet("QTabBar::tab{width:200px;}")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setStyleSheet("font: 14pt \"幼圆\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.LineApkdirPath = QtWidgets.QLineEdit(self.tab_3)
        self.LineApkdirPath.setMinimumSize(QtCore.QSize(0, 40))
        self.LineApkdirPath.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.LineApkdirPath.setObjectName("LineApkdirPath")
        self.verticalLayout_4.addWidget(self.LineApkdirPath)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.SelectOnline = QtWidgets.QPushButton(self.tab_3)
        self.SelectOnline.setMinimumSize(QtCore.QSize(0, 80))
        self.SelectOnline.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.SelectOnline.setObjectName("SelectOnline")
        self.horizontalLayout_2.addWidget(self.SelectOnline)
        self.ClearOnlineText = QtWidgets.QPushButton(self.tab_3)
        self.ClearOnlineText.setMinimumSize(QtCore.QSize(0, 80))
        self.ClearOnlineText.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.ClearOnlineText.setObjectName("ClearOnlineText")
        self.horizontalLayout_2.addWidget(self.ClearOnlineText)
        self.horizontalLayout_2.setStretch(0, 8)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.FailConfig = QtWidgets.QTextBrowser(self.tab_3)
        self.FailConfig.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.FailConfig.setObjectName("FailConfig")
        self.verticalLayout_5.addWidget(self.FailConfig)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.SucConfig = QtWidgets.QTextBrowser(self.tab_3)
        self.SucConfig.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.SucConfig.setObjectName("SucConfig")
        self.verticalLayout_6.addWidget(self.SucConfig)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 9)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.SelectPrid = QtWidgets.QLineEdit(self.tab_4)
        self.SelectPrid.setMinimumSize(QtCore.QSize(0, 40))
        self.SelectPrid.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.SelectPrid.setObjectName("SelectPrid")
        self.horizontalLayout_4.addWidget(self.SelectPrid)
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.SelectChan = QtWidgets.QLineEdit(self.tab_4)
        self.SelectChan.setMinimumSize(QtCore.QSize(0, 40))
        self.SelectChan.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.SelectChan.setObjectName("SelectChan")
        self.horizontalLayout_4.addWidget(self.SelectChan)
        self.SelectAd = QtWidgets.QPushButton(self.tab_4)
        self.SelectAd.setMinimumSize(QtCore.QSize(0, 40))
        self.SelectAd.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.SelectAd.setObjectName("SelectAd")
        self.horizontalLayout_4.addWidget(self.SelectAd)
        self.ClearAdText = QtWidgets.QPushButton(self.tab_4)
        self.ClearAdText.setMinimumSize(QtCore.QSize(0, 40))
        self.ClearAdText.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.ClearAdText.setObjectName("ClearAdText")
        self.horizontalLayout_4.addWidget(self.ClearAdText)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 2)
        self.horizontalLayout_4.setStretch(4, 2)
        self.horizontalLayout_4.setStretch(5, 2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.AllGroupText = QtWidgets.QTextBrowser(self.tab_4)
        self.AllGroupText.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AllGroupText.setObjectName("AllGroupText")
        self.verticalLayout_10.addWidget(self.AllGroupText)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.AGroupText = QtWidgets.QTextBrowser(self.tab_4)
        self.AGroupText.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AGroupText.setObjectName("AGroupText")
        self.verticalLayout_9.addWidget(self.AGroupText)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.BGroupText = QtWidgets.QTextBrowser(self.tab_4)
        self.BGroupText.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.BGroupText.setObjectName("BGroupText")
        self.verticalLayout_8.addWidget(self.BGroupText)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.CGroupText = QtWidgets.QTextBrowser(self.tab_4)
        self.CGroupText.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.CGroupText.setObjectName("CGroupText")
        self.verticalLayout_11.addWidget(self.CGroupText)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_4.setStyleSheet("QTabBar::tab{width:300px;}")
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_11)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.tab_11)
        self.label_11.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.SplashCfgText = QtWidgets.QTextBrowser(self.tab_11)
        self.SplashCfgText.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.SplashCfgText.setObjectName("SplashCfgText")
        self.verticalLayout_14.addWidget(self.SplashCfgText)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.tab_11)
        self.label_12.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.MsgCfgText = QtWidgets.QTextBrowser(self.tab_11)
        self.MsgCfgText.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.MsgCfgText.setObjectName("MsgCfgText")
        self.verticalLayout_15.addWidget(self.MsgCfgText)
        self.horizontalLayout_6.addLayout(self.verticalLayout_15)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.tab_11)
        self.label_10.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.PlaqueCfgText = QtWidgets.QTextBrowser(self.tab_11)
        self.PlaqueCfgText.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.PlaqueCfgText.setObjectName("PlaqueCfgText")
        self.verticalLayout_13.addWidget(self.PlaqueCfgText)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.tab_11)
        self.label_13.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_16.addWidget(self.label_13)
        self.VideoCfgText = QtWidgets.QTextBrowser(self.tab_11)
        self.VideoCfgText.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.VideoCfgText.setObjectName("VideoCfgText")
        self.verticalLayout_16.addWidget(self.VideoCfgText)
        self.horizontalLayout_6.addLayout(self.verticalLayout_16)
        self.tabWidget_4.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.tab_12)
        self.label_15.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_18.addWidget(self.label_15)
        self.SplashSourceText = QtWidgets.QTextBrowser(self.tab_12)
        self.SplashSourceText.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.SplashSourceText.setObjectName("SplashSourceText")
        self.verticalLayout_18.addWidget(self.SplashSourceText)
        self.horizontalLayout_7.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_16 = QtWidgets.QLabel(self.tab_12)
        self.label_16.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_19.addWidget(self.label_16)
        self.MsgSourceText = QtWidgets.QTextBrowser(self.tab_12)
        self.MsgSourceText.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.MsgSourceText.setObjectName("MsgSourceText")
        self.verticalLayout_19.addWidget(self.MsgSourceText)
        self.horizontalLayout_7.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_17 = QtWidgets.QLabel(self.tab_12)
        self.label_17.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_20.addWidget(self.label_17)
        self.PlaqueSourceText = QtWidgets.QTextBrowser(self.tab_12)
        self.PlaqueSourceText.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.PlaqueSourceText.setObjectName("PlaqueSourceText")
        self.verticalLayout_20.addWidget(self.PlaqueSourceText)
        self.horizontalLayout_7.addLayout(self.verticalLayout_20)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.tab_12)
        self.label_14.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_17.addWidget(self.label_14)
        self.VideoSourceText = QtWidgets.QTextBrowser(self.tab_12)
        self.VideoSourceText.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.VideoSourceText.setObjectName("VideoSourceText")
        self.verticalLayout_17.addWidget(self.VideoSourceText)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.tabWidget_4.addTab(self.tab_12, "")
        self.verticalLayout_12.addWidget(self.tabWidget_4)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 3)
        self.verticalLayout_12.setStretch(2, 6)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.VerifyPrid = QtWidgets.QLineEdit(self.tab_5)
        self.VerifyPrid.setMinimumSize(QtCore.QSize(0, 40))
        self.VerifyPrid.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.VerifyPrid.setObjectName("VerifyPrid")
        self.horizontalLayout_8.addWidget(self.VerifyPrid)
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_8.addWidget(self.label_19)
        self.VerifyChan = QtWidgets.QLineEdit(self.tab_5)
        self.VerifyChan.setMinimumSize(QtCore.QSize(0, 40))
        self.VerifyChan.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.VerifyChan.setObjectName("VerifyChan")
        self.horizontalLayout_8.addWidget(self.VerifyChan)
        self.verticalLayout_21.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.PackageInfo = QtWidgets.QLineEdit(self.tab_5)
        self.PackageInfo.setMinimumSize(QtCore.QSize(0, 40))
        self.PackageInfo.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.PackageInfo.setObjectName("PackageInfo")
        self.horizontalLayout_9.addWidget(self.PackageInfo)
        self.verticalLayout_21.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_21)
        self.VerifyAd = QtWidgets.QPushButton(self.tab_5)
        self.VerifyAd.setMinimumSize(QtCore.QSize(0, 90))
        self.VerifyAd.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 28pt \"幼圆\";}")
        self.VerifyAd.setObjectName("VerifyAd")
        self.horizontalLayout_10.addWidget(self.VerifyAd)
        self.ClearVerifyAdText = QtWidgets.QPushButton(self.tab_5)
        self.ClearVerifyAdText.setMinimumSize(QtCore.QSize(0, 90))
        self.ClearVerifyAdText.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 28pt \"幼圆\";}")
        self.ClearVerifyAdText.setObjectName("ClearVerifyAdText")
        self.horizontalLayout_10.addWidget(self.ClearVerifyAdText)
        self.horizontalLayout_10.setStretch(0, 6)
        self.horizontalLayout_10.setStretch(1, 2)
        self.horizontalLayout_10.setStretch(2, 2)
        self.verticalLayout_25.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_22.addWidget(self.label_21)
        self.MatchText = QtWidgets.QTextBrowser(self.tab_5)
        self.MatchText.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.MatchText.setObjectName("MatchText")
        self.verticalLayout_22.addWidget(self.MatchText)
        self.horizontalLayout_11.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_23.addWidget(self.label_22)
        self.LackText = QtWidgets.QTextBrowser(self.tab_5)
        self.LackText.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.LackText.setObjectName("LackText")
        self.verticalLayout_23.addWidget(self.LackText)
        self.horizontalLayout_11.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_24.addWidget(self.label_23)
        self.TmrText = QtWidgets.QTextBrowser(self.tab_5)
        self.TmrText.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.TmrText.setObjectName("TmrText")
        self.verticalLayout_24.addWidget(self.TmrText)
        self.horizontalLayout_11.addLayout(self.verticalLayout_24)
        self.verticalLayout_25.addLayout(self.horizontalLayout_11)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DevicesList = QtWidgets.QComboBox(self.tab_2)
        self.DevicesList.setMinimumSize(QtCore.QSize(0, 40))
        self.DevicesList.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.DevicesList.setObjectName("DevicesList")
        self.horizontalLayout.addWidget(self.DevicesList)
        self.DevicesRefresh = QtWidgets.QPushButton(self.tab_2)
        self.DevicesRefresh.setMinimumSize(QtCore.QSize(0, 40))
        self.DevicesRefresh.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.DevicesRefresh.setObjectName("DevicesRefresh")
        self.horizontalLayout.addWidget(self.DevicesRefresh)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_3.setStyleSheet("QTabBar::tab{width:180px;}")
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_24 = QtWidgets.QLabel(self.tab_10)
        self.label_24.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_12.addWidget(self.label_24)
        self.ImgDriName = QtWidgets.QLineEdit(self.tab_10)
        self.ImgDriName.setMinimumSize(QtCore.QSize(0, 40))
        self.ImgDriName.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.ImgDriName.setObjectName("ImgDriName")
        self.horizontalLayout_12.addWidget(self.ImgDriName)
        self.ImgMkdirName = QtWidgets.QPushButton(self.tab_10)
        self.ImgMkdirName.setMinimumSize(QtCore.QSize(0, 40))
        self.ImgMkdirName.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.ImgMkdirName.setObjectName("ImgMkdirName")
        self.horizontalLayout_12.addWidget(self.ImgMkdirName)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 8)
        self.horizontalLayout_12.setStretch(2, 2)
        self.verticalLayout_31.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.ImgOne = QtWidgets.QLabel(self.tab_10)
        self.ImgOne.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.ImgOne.setAlignment(QtCore.Qt.AlignCenter)
        self.ImgOne.setObjectName("ImgOne")
        self.verticalLayout_27.addWidget(self.ImgOne)
        self.ScreenOne = QtWidgets.QPushButton(self.tab_10)
        self.ScreenOne.setMinimumSize(QtCore.QSize(0, 40))
        self.ScreenOne.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.ScreenOne.setObjectName("ScreenOne")
        self.verticalLayout_27.addWidget(self.ScreenOne)
        self.horizontalLayout_13.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.ImgTwo = QtWidgets.QLabel(self.tab_10)
        self.ImgTwo.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.ImgTwo.setAlignment(QtCore.Qt.AlignCenter)
        self.ImgTwo.setObjectName("ImgTwo")
        self.verticalLayout_28.addWidget(self.ImgTwo)
        self.ScreenTwo = QtWidgets.QPushButton(self.tab_10)
        self.ScreenTwo.setMinimumSize(QtCore.QSize(0, 40))
        self.ScreenTwo.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.ScreenTwo.setObjectName("ScreenTwo")
        self.verticalLayout_28.addWidget(self.ScreenTwo)
        self.horizontalLayout_13.addLayout(self.verticalLayout_28)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.ImgThree = QtWidgets.QLabel(self.tab_10)
        self.ImgThree.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.ImgThree.setAlignment(QtCore.Qt.AlignCenter)
        self.ImgThree.setObjectName("ImgThree")
        self.verticalLayout_30.addWidget(self.ImgThree)
        self.ScreenThree = QtWidgets.QPushButton(self.tab_10)
        self.ScreenThree.setMinimumSize(QtCore.QSize(0, 40))
        self.ScreenThree.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.ScreenThree.setObjectName("ScreenThree")
        self.verticalLayout_30.addWidget(self.ScreenThree)
        self.horizontalLayout_13.addLayout(self.verticalLayout_30)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.ImgFour = QtWidgets.QLabel(self.tab_10)
        self.ImgFour.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.ImgFour.setAlignment(QtCore.Qt.AlignCenter)
        self.ImgFour.setObjectName("ImgFour")
        self.verticalLayout_29.addWidget(self.ImgFour)
        self.ScreenFour = QtWidgets.QPushButton(self.tab_10)
        self.ScreenFour.setMinimumSize(QtCore.QSize(0, 40))
        self.ScreenFour.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.ScreenFour.setObjectName("ScreenFour")
        self.verticalLayout_29.addWidget(self.ScreenFour)
        self.horizontalLayout_13.addLayout(self.verticalLayout_29)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.ImgFive = QtWidgets.QLabel(self.tab_10)
        self.ImgFive.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.ImgFive.setAlignment(QtCore.Qt.AlignCenter)
        self.ImgFive.setObjectName("ImgFive")
        self.verticalLayout_26.addWidget(self.ImgFive)
        self.ScreenFive = QtWidgets.QPushButton(self.tab_10)
        self.ScreenFive.setMinimumSize(QtCore.QSize(0, 40))
        self.ScreenFive.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.ScreenFive.setObjectName("ScreenFive")
        self.verticalLayout_26.addWidget(self.ScreenFive)
        self.horizontalLayout_13.addLayout(self.verticalLayout_26)
        self.verticalLayout_31.addLayout(self.horizontalLayout_13)
        self.verticalLayout_31.setStretch(0, 1)
        self.verticalLayout_31.setStretch(1, 8)
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.TestToolsPathText = QtWidgets.QLineEdit(self.tab_9)
        self.TestToolsPathText.setMinimumSize(QtCore.QSize(0, 40))
        self.TestToolsPathText.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.TestToolsPathText.setObjectName("TestToolsPathText")
        self.horizontalLayout_14.addWidget(self.TestToolsPathText)
        self.ClearPathText = QtWidgets.QPushButton(self.tab_9)
        self.ClearPathText.setMinimumSize(QtCore.QSize(80, 40))
        self.ClearPathText.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.ClearPathText.setObjectName("ClearPathText")
        self.horizontalLayout_14.addWidget(self.ClearPathText)
        self.verticalLayout_32.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_30 = QtWidgets.QLabel(self.tab_9)
        self.label_30.setMinimumSize(QtCore.QSize(0, 40))
        self.label_30.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_15.addWidget(self.label_30)
        self.DemoApp = QtWidgets.QComboBox(self.tab_9)
        self.DemoApp.setMinimumSize(QtCore.QSize(0, 40))
        self.DemoApp.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.DemoApp.setObjectName("DemoApp")
        self.DemoApp.addItem("")
        self.DemoApp.addItem("")
        self.DemoApp.addItem("")
        self.DemoApp.addItem("")
        self.DemoApp.addItem("")
        self.DemoApp.addItem("")
        self.DemoApp.addItem("")
        self.horizontalLayout_15.addWidget(self.DemoApp)
        self.InstallApp = QtWidgets.QPushButton(self.tab_9)
        self.InstallApp.setMinimumSize(QtCore.QSize(0, 40))
        self.InstallApp.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.InstallApp.setObjectName("InstallApp")
        self.horizontalLayout_15.addWidget(self.InstallApp)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 8)
        self.horizontalLayout_15.setStretch(2, 2)
        self.verticalLayout_32.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.StartApp = QtWidgets.QPushButton(self.tab_9)
        self.StartApp.setMinimumSize(QtCore.QSize(0, 40))
        self.StartApp.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.StartApp.setObjectName("StartApp")
        self.horizontalLayout_16.addWidget(self.StartApp)
        self.CheckProcess = QtWidgets.QPushButton(self.tab_9)
        self.CheckProcess.setMinimumSize(QtCore.QSize(0, 40))
        self.CheckProcess.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.CheckProcess.setObjectName("CheckProcess")
        self.horizontalLayout_16.addWidget(self.CheckProcess)
        self.StopApp = QtWidgets.QPushButton(self.tab_9)
        self.StopApp.setMinimumSize(QtCore.QSize(0, 40))
        self.StopApp.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.StopApp.setObjectName("StopApp")
        self.horizontalLayout_16.addWidget(self.StopApp)
        self.UninstallApp = QtWidgets.QPushButton(self.tab_9)
        self.UninstallApp.setMinimumSize(QtCore.QSize(0, 40))
        self.UninstallApp.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.UninstallApp.setObjectName("UninstallApp")
        self.horizontalLayout_16.addWidget(self.UninstallApp)
        self.ClearApp = QtWidgets.QPushButton(self.tab_9)
        self.ClearApp.setMinimumSize(QtCore.QSize(180, 40))
        self.ClearApp.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.ClearApp.setObjectName("ClearApp")
        self.horizontalLayout_16.addWidget(self.ClearApp)
        self.DebugApp = QtWidgets.QPushButton(self.tab_9)
        self.DebugApp.setMinimumSize(QtCore.QSize(0, 40))
        self.DebugApp.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.DebugApp.setObjectName("DebugApp")
        self.horizontalLayout_16.addWidget(self.DebugApp)
        self.UndebugApp = QtWidgets.QPushButton(self.tab_9)
        self.UndebugApp.setMinimumSize(QtCore.QSize(0, 40))
        self.UndebugApp.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.UndebugApp.setObjectName("UndebugApp")
        self.horizontalLayout_16.addWidget(self.UndebugApp)
        self.verticalLayout_32.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_31 = QtWidgets.QLabel(self.tab_9)
        self.label_31.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_17.addWidget(self.label_31)
        self.ProcessText = QtWidgets.QTextBrowser(self.tab_9)
        self.ProcessText.setStyleSheet("border-radius: 20px;\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.ProcessText.setObjectName("ProcessText")
        self.horizontalLayout_17.addWidget(self.ProcessText)
        self.ClearProcessText = QtWidgets.QPushButton(self.tab_9)
        self.ClearProcessText.setMinimumSize(QtCore.QSize(70, 420))
        self.ClearProcessText.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.ClearProcessText.setObjectName("ClearProcessText")
        self.horizontalLayout_17.addWidget(self.ClearProcessText)
        self.verticalLayout_32.addLayout(self.horizontalLayout_17)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.AutoPathText = QtWidgets.QLineEdit(self.tab_7)
        self.AutoPathText.setMinimumSize(QtCore.QSize(0, 50))
        self.AutoPathText.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoPathText.setObjectName("AutoPathText")
        self.horizontalLayout_18.addWidget(self.AutoPathText)
        self.AutoStart = QtWidgets.QPushButton(self.tab_7)
        self.AutoStart.setMinimumSize(QtCore.QSize(0, 50))
        self.AutoStart.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoStart.setObjectName("AutoStart")
        self.horizontalLayout_18.addWidget(self.AutoStart)
        self.AutoClearPathText = QtWidgets.QPushButton(self.tab_7)
        self.AutoClearPathText.setMinimumSize(QtCore.QSize(120, 50))
        self.AutoClearPathText.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoClearPathText.setObjectName("AutoClearPathText")
        self.horizontalLayout_18.addWidget(self.AutoClearPathText)
        self.verticalLayout_33.addLayout(self.horizontalLayout_18)
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_7)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.tab_13)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_32 = QtWidgets.QLabel(self.tab_13)
        self.label_32.setStyleSheet("font: 28pt \"幼圆\";")
        self.label_32.setObjectName("label_32")
        self.verticalLayout_34.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.tab_13)
        self.label_33.setStyleSheet("font: 14pt \"幼圆\";\n"
"color: rgb(255, 85, 0);")
        self.label_33.setObjectName("label_33")
        self.verticalLayout_34.addWidget(self.label_33)
        self.AutoInfo = QtWidgets.QTextBrowser(self.tab_13)
        self.AutoInfo.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoInfo.setObjectName("AutoInfo")
        self.verticalLayout_34.addWidget(self.AutoInfo)
        self.tabWidget_5.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.tab_14)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.AutoLockImg = QtWidgets.QLabel(self.tab_14)
        self.AutoLockImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AutoLockImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AutoLockImg.setObjectName("AutoLockImg")
        self.verticalLayout_35.addWidget(self.AutoLockImg)
        self.AutoLockPath = QtWidgets.QTextBrowser(self.tab_14)
        self.AutoLockPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoLockPath.setObjectName("AutoLockPath")
        self.verticalLayout_35.addWidget(self.AutoLockPath)
        self.AutoLockLook = QtWidgets.QPushButton(self.tab_14)
        self.AutoLockLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoLockLook.setObjectName("AutoLockLook")
        self.verticalLayout_35.addWidget(self.AutoLockLook)
        self.verticalLayout_35.setStretch(0, 8)
        self.verticalLayout_35.setStretch(1, 1)
        self.verticalLayout_35.setStretch(2, 1)
        self.horizontalLayout_20.addLayout(self.verticalLayout_35)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.AutoUnlockImg = QtWidgets.QLabel(self.tab_14)
        self.AutoUnlockImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AutoUnlockImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AutoUnlockImg.setObjectName("AutoUnlockImg")
        self.verticalLayout_40.addWidget(self.AutoUnlockImg)
        self.AutoUnlockPath = QtWidgets.QTextBrowser(self.tab_14)
        self.AutoUnlockPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoUnlockPath.setObjectName("AutoUnlockPath")
        self.verticalLayout_40.addWidget(self.AutoUnlockPath)
        self.AutoUnlockLook = QtWidgets.QPushButton(self.tab_14)
        self.AutoUnlockLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoUnlockLook.setObjectName("AutoUnlockLook")
        self.verticalLayout_40.addWidget(self.AutoUnlockLook)
        self.verticalLayout_40.setStretch(0, 8)
        self.verticalLayout_40.setStretch(1, 1)
        self.verticalLayout_40.setStretch(2, 1)
        self.horizontalLayout_20.addLayout(self.verticalLayout_40)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.AutoChargeImg = QtWidgets.QLabel(self.tab_14)
        self.AutoChargeImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AutoChargeImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AutoChargeImg.setObjectName("AutoChargeImg")
        self.verticalLayout_36.addWidget(self.AutoChargeImg)
        self.AutoChargePath = QtWidgets.QTextBrowser(self.tab_14)
        self.AutoChargePath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoChargePath.setObjectName("AutoChargePath")
        self.verticalLayout_36.addWidget(self.AutoChargePath)
        self.AutoChargeLook = QtWidgets.QPushButton(self.tab_14)
        self.AutoChargeLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoChargeLook.setObjectName("AutoChargeLook")
        self.verticalLayout_36.addWidget(self.AutoChargeLook)
        self.verticalLayout_36.setStretch(0, 8)
        self.verticalLayout_36.setStretch(1, 1)
        self.verticalLayout_36.setStretch(2, 1)
        self.horizontalLayout_20.addLayout(self.verticalLayout_36)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.AutoWifiImg = QtWidgets.QLabel(self.tab_14)
        self.AutoWifiImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AutoWifiImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AutoWifiImg.setObjectName("AutoWifiImg")
        self.verticalLayout_39.addWidget(self.AutoWifiImg)
        self.AutoWifiPath = QtWidgets.QTextBrowser(self.tab_14)
        self.AutoWifiPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoWifiPath.setObjectName("AutoWifiPath")
        self.verticalLayout_39.addWidget(self.AutoWifiPath)
        self.AutoWifiLook = QtWidgets.QPushButton(self.tab_14)
        self.AutoWifiLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoWifiLook.setObjectName("AutoWifiLook")
        self.verticalLayout_39.addWidget(self.AutoWifiLook)
        self.verticalLayout_39.setStretch(0, 8)
        self.verticalLayout_39.setStretch(1, 1)
        self.verticalLayout_39.setStretch(2, 1)
        self.horizontalLayout_20.addLayout(self.verticalLayout_39)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.AutoTimerImg = QtWidgets.QLabel(self.tab_14)
        self.AutoTimerImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AutoTimerImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AutoTimerImg.setObjectName("AutoTimerImg")
        self.verticalLayout_38.addWidget(self.AutoTimerImg)
        self.AutoTimerPath = QtWidgets.QTextBrowser(self.tab_14)
        self.AutoTimerPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoTimerPath.setObjectName("AutoTimerPath")
        self.verticalLayout_38.addWidget(self.AutoTimerPath)
        self.AutoTimerLook = QtWidgets.QPushButton(self.tab_14)
        self.AutoTimerLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoTimerLook.setObjectName("AutoTimerLook")
        self.verticalLayout_38.addWidget(self.AutoTimerLook)
        self.verticalLayout_38.setStretch(0, 8)
        self.verticalLayout_38.setStretch(1, 1)
        self.verticalLayout_38.setStretch(2, 1)
        self.horizontalLayout_20.addLayout(self.verticalLayout_38)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.AutoHomeImg = QtWidgets.QLabel(self.tab_14)
        self.AutoHomeImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AutoHomeImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AutoHomeImg.setObjectName("AutoHomeImg")
        self.verticalLayout_37.addWidget(self.AutoHomeImg)
        self.AutoHomePath = QtWidgets.QTextBrowser(self.tab_14)
        self.AutoHomePath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoHomePath.setObjectName("AutoHomePath")
        self.verticalLayout_37.addWidget(self.AutoHomePath)
        self.AutoHomeLook = QtWidgets.QPushButton(self.tab_14)
        self.AutoHomeLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoHomeLook.setObjectName("AutoHomeLook")
        self.verticalLayout_37.addWidget(self.AutoHomeLook)
        self.verticalLayout_37.setStretch(0, 8)
        self.verticalLayout_37.setStretch(1, 1)
        self.verticalLayout_37.setStretch(2, 1)
        self.horizontalLayout_20.addLayout(self.verticalLayout_37)
        self.tabWidget_5.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.tab_15)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.AutoAdUnlockImg = QtWidgets.QLabel(self.tab_15)
        self.AutoAdUnlockImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AutoAdUnlockImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AutoAdUnlockImg.setObjectName("AutoAdUnlockImg")
        self.verticalLayout_41.addWidget(self.AutoAdUnlockImg)
        self.label_40 = QtWidgets.QLabel(self.tab_15)
        self.label_40.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_41.addWidget(self.label_40)
        self.AutoAdUnlockPath = QtWidgets.QTextBrowser(self.tab_15)
        self.AutoAdUnlockPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoAdUnlockPath.setObjectName("AutoAdUnlockPath")
        self.verticalLayout_41.addWidget(self.AutoAdUnlockPath)
        self.AutoAdUnlockLook = QtWidgets.QPushButton(self.tab_15)
        self.AutoAdUnlockLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoAdUnlockLook.setObjectName("AutoAdUnlockLook")
        self.verticalLayout_41.addWidget(self.AutoAdUnlockLook)
        self.verticalLayout_41.setStretch(0, 8)
        self.verticalLayout_41.setStretch(2, 1)
        self.verticalLayout_41.setStretch(3, 1)
        self.horizontalLayout_21.addLayout(self.verticalLayout_41)
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.AutoAdChargeImg = QtWidgets.QLabel(self.tab_15)
        self.AutoAdChargeImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AutoAdChargeImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AutoAdChargeImg.setObjectName("AutoAdChargeImg")
        self.verticalLayout_42.addWidget(self.AutoAdChargeImg)
        self.label_43 = QtWidgets.QLabel(self.tab_15)
        self.label_43.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_42.addWidget(self.label_43)
        self.AutoAdChargePath = QtWidgets.QTextBrowser(self.tab_15)
        self.AutoAdChargePath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoAdChargePath.setObjectName("AutoAdChargePath")
        self.verticalLayout_42.addWidget(self.AutoAdChargePath)
        self.AutoAdChargeLook = QtWidgets.QPushButton(self.tab_15)
        self.AutoAdChargeLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoAdChargeLook.setObjectName("AutoAdChargeLook")
        self.verticalLayout_42.addWidget(self.AutoAdChargeLook)
        self.verticalLayout_42.setStretch(0, 8)
        self.verticalLayout_42.setStretch(2, 1)
        self.verticalLayout_42.setStretch(3, 1)
        self.horizontalLayout_21.addLayout(self.verticalLayout_42)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.AutoAdHomeImg = QtWidgets.QLabel(self.tab_15)
        self.AutoAdHomeImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AutoAdHomeImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AutoAdHomeImg.setObjectName("AutoAdHomeImg")
        self.verticalLayout_43.addWidget(self.AutoAdHomeImg)
        self.label_45 = QtWidgets.QLabel(self.tab_15)
        self.label_45.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_43.addWidget(self.label_45)
        self.AutoAdHomePath = QtWidgets.QTextBrowser(self.tab_15)
        self.AutoAdHomePath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoAdHomePath.setObjectName("AutoAdHomePath")
        self.verticalLayout_43.addWidget(self.AutoAdHomePath)
        self.AutoAdHomeLook = QtWidgets.QPushButton(self.tab_15)
        self.AutoAdHomeLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoAdHomeLook.setObjectName("AutoAdHomeLook")
        self.verticalLayout_43.addWidget(self.AutoAdHomeLook)
        self.verticalLayout_43.setStretch(0, 8)
        self.verticalLayout_43.setStretch(2, 1)
        self.verticalLayout_43.setStretch(3, 1)
        self.horizontalLayout_21.addLayout(self.verticalLayout_43)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.AutoAdWifiImg = QtWidgets.QLabel(self.tab_15)
        self.AutoAdWifiImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AutoAdWifiImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AutoAdWifiImg.setObjectName("AutoAdWifiImg")
        self.verticalLayout_44.addWidget(self.AutoAdWifiImg)
        self.label_47 = QtWidgets.QLabel(self.tab_15)
        self.label_47.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_44.addWidget(self.label_47)
        self.AutoAdWifiPath = QtWidgets.QTextBrowser(self.tab_15)
        self.AutoAdWifiPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoAdWifiPath.setObjectName("AutoAdWifiPath")
        self.verticalLayout_44.addWidget(self.AutoAdWifiPath)
        self.AutoAdWifiLook = QtWidgets.QPushButton(self.tab_15)
        self.AutoAdWifiLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoAdWifiLook.setObjectName("AutoAdWifiLook")
        self.verticalLayout_44.addWidget(self.AutoAdWifiLook)
        self.verticalLayout_44.setStretch(0, 8)
        self.verticalLayout_44.setStretch(2, 1)
        self.verticalLayout_44.setStretch(3, 1)
        self.horizontalLayout_21.addLayout(self.verticalLayout_44)
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.AutoAdTimerImg = QtWidgets.QLabel(self.tab_15)
        self.AutoAdTimerImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AutoAdTimerImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AutoAdTimerImg.setObjectName("AutoAdTimerImg")
        self.verticalLayout_45.addWidget(self.AutoAdTimerImg)
        self.label_49 = QtWidgets.QLabel(self.tab_15)
        self.label_49.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_45.addWidget(self.label_49)
        self.AutoAdTimerPath = QtWidgets.QTextBrowser(self.tab_15)
        self.AutoAdTimerPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AutoAdTimerPath.setObjectName("AutoAdTimerPath")
        self.verticalLayout_45.addWidget(self.AutoAdTimerPath)
        self.AutoAdTimerLook = QtWidgets.QPushButton(self.tab_15)
        self.AutoAdTimerLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AutoAdTimerLook.setObjectName("AutoAdTimerLook")
        self.verticalLayout_45.addWidget(self.AutoAdTimerLook)
        self.verticalLayout_45.setStretch(0, 8)
        self.verticalLayout_45.setStretch(2, 1)
        self.verticalLayout_45.setStretch(3, 1)
        self.horizontalLayout_21.addLayout(self.verticalLayout_45)
        self.tabWidget_5.addTab(self.tab_15, "")
        self.verticalLayout_33.addWidget(self.tabWidget_5)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.AshingPathText = QtWidgets.QLineEdit(self.tab_8)
        self.AshingPathText.setMinimumSize(QtCore.QSize(0, 50))
        self.AshingPathText.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingPathText.setObjectName("AshingPathText")
        self.horizontalLayout_19.addWidget(self.AshingPathText)
        self.AshingStart = QtWidgets.QPushButton(self.tab_8)
        self.AshingStart.setMinimumSize(QtCore.QSize(0, 50))
        self.AshingStart.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingStart.setObjectName("AshingStart")
        self.horizontalLayout_19.addWidget(self.AshingStart)
        self.AshingClearPathText = QtWidgets.QPushButton(self.tab_8)
        self.AshingClearPathText.setMinimumSize(QtCore.QSize(120, 50))
        self.AshingClearPathText.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingClearPathText.setObjectName("AshingClearPathText")
        self.horizontalLayout_19.addWidget(self.AshingClearPathText)
        self.verticalLayout_58.addLayout(self.horizontalLayout_19)
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_8)
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.tab_16)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.label_50 = QtWidgets.QLabel(self.tab_16)
        self.label_50.setStyleSheet("font: 28pt \"幼圆\";")
        self.label_50.setObjectName("label_50")
        self.verticalLayout_46.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.tab_16)
        self.label_51.setStyleSheet("font: 14pt \"幼圆\";\n"
"color: rgb(255, 85, 0);")
        self.label_51.setObjectName("label_51")
        self.verticalLayout_46.addWidget(self.label_51)
        self.AshingInfo = QtWidgets.QTextBrowser(self.tab_16)
        self.AshingInfo.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingInfo.setObjectName("AshingInfo")
        self.verticalLayout_46.addWidget(self.AshingInfo)
        self.tabWidget_6.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.tab_17)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.AshingLockImg = QtWidgets.QLabel(self.tab_17)
        self.AshingLockImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AshingLockImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AshingLockImg.setObjectName("AshingLockImg")
        self.verticalLayout_47.addWidget(self.AshingLockImg)
        self.AshingLockPath = QtWidgets.QTextBrowser(self.tab_17)
        self.AshingLockPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingLockPath.setObjectName("AshingLockPath")
        self.verticalLayout_47.addWidget(self.AshingLockPath)
        self.AshingLockLook = QtWidgets.QPushButton(self.tab_17)
        self.AshingLockLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingLockLook.setObjectName("AshingLockLook")
        self.verticalLayout_47.addWidget(self.AshingLockLook)
        self.verticalLayout_47.setStretch(0, 8)
        self.verticalLayout_47.setStretch(1, 1)
        self.verticalLayout_47.setStretch(2, 1)
        self.horizontalLayout_22.addLayout(self.verticalLayout_47)
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.AshingUnlockImg = QtWidgets.QLabel(self.tab_17)
        self.AshingUnlockImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AshingUnlockImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AshingUnlockImg.setObjectName("AshingUnlockImg")
        self.verticalLayout_48.addWidget(self.AshingUnlockImg)
        self.AshingUnlockPath = QtWidgets.QTextBrowser(self.tab_17)
        self.AshingUnlockPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingUnlockPath.setObjectName("AshingUnlockPath")
        self.verticalLayout_48.addWidget(self.AshingUnlockPath)
        self.AshingUnlockLook = QtWidgets.QPushButton(self.tab_17)
        self.AshingUnlockLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingUnlockLook.setObjectName("AshingUnlockLook")
        self.verticalLayout_48.addWidget(self.AshingUnlockLook)
        self.verticalLayout_48.setStretch(0, 8)
        self.verticalLayout_48.setStretch(1, 1)
        self.verticalLayout_48.setStretch(2, 1)
        self.horizontalLayout_22.addLayout(self.verticalLayout_48)
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.AshingChargeImg = QtWidgets.QLabel(self.tab_17)
        self.AshingChargeImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AshingChargeImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AshingChargeImg.setObjectName("AshingChargeImg")
        self.verticalLayout_49.addWidget(self.AshingChargeImg)
        self.AshingChargePath = QtWidgets.QTextBrowser(self.tab_17)
        self.AshingChargePath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingChargePath.setObjectName("AshingChargePath")
        self.verticalLayout_49.addWidget(self.AshingChargePath)
        self.AshingChargeLook = QtWidgets.QPushButton(self.tab_17)
        self.AshingChargeLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingChargeLook.setObjectName("AshingChargeLook")
        self.verticalLayout_49.addWidget(self.AshingChargeLook)
        self.verticalLayout_49.setStretch(0, 8)
        self.verticalLayout_49.setStretch(1, 1)
        self.verticalLayout_49.setStretch(2, 1)
        self.horizontalLayout_22.addLayout(self.verticalLayout_49)
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.AshingWifiImg = QtWidgets.QLabel(self.tab_17)
        self.AshingWifiImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AshingWifiImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AshingWifiImg.setObjectName("AshingWifiImg")
        self.verticalLayout_50.addWidget(self.AshingWifiImg)
        self.AshingWifiPath = QtWidgets.QTextBrowser(self.tab_17)
        self.AshingWifiPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingWifiPath.setObjectName("AshingWifiPath")
        self.verticalLayout_50.addWidget(self.AshingWifiPath)
        self.AshingWifiLook = QtWidgets.QPushButton(self.tab_17)
        self.AshingWifiLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingWifiLook.setObjectName("AshingWifiLook")
        self.verticalLayout_50.addWidget(self.AshingWifiLook)
        self.verticalLayout_50.setStretch(0, 8)
        self.verticalLayout_50.setStretch(1, 1)
        self.verticalLayout_50.setStretch(2, 1)
        self.horizontalLayout_22.addLayout(self.verticalLayout_50)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.AshingTimerImg = QtWidgets.QLabel(self.tab_17)
        self.AshingTimerImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AshingTimerImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AshingTimerImg.setObjectName("AshingTimerImg")
        self.verticalLayout_51.addWidget(self.AshingTimerImg)
        self.AshingTimerPath = QtWidgets.QTextBrowser(self.tab_17)
        self.AshingTimerPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingTimerPath.setObjectName("AshingTimerPath")
        self.verticalLayout_51.addWidget(self.AshingTimerPath)
        self.AshingTimerLook = QtWidgets.QPushButton(self.tab_17)
        self.AshingTimerLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingTimerLook.setObjectName("AshingTimerLook")
        self.verticalLayout_51.addWidget(self.AshingTimerLook)
        self.verticalLayout_51.setStretch(0, 8)
        self.verticalLayout_51.setStretch(1, 1)
        self.verticalLayout_51.setStretch(2, 1)
        self.horizontalLayout_22.addLayout(self.verticalLayout_51)
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.AshingHomeImg = QtWidgets.QLabel(self.tab_17)
        self.AshingHomeImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AshingHomeImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AshingHomeImg.setObjectName("AshingHomeImg")
        self.verticalLayout_52.addWidget(self.AshingHomeImg)
        self.AshingHomePath = QtWidgets.QTextBrowser(self.tab_17)
        self.AshingHomePath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingHomePath.setObjectName("AshingHomePath")
        self.verticalLayout_52.addWidget(self.AshingHomePath)
        self.AshingHomeLook = QtWidgets.QPushButton(self.tab_17)
        self.AshingHomeLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingHomeLook.setObjectName("AshingHomeLook")
        self.verticalLayout_52.addWidget(self.AshingHomeLook)
        self.verticalLayout_52.setStretch(0, 8)
        self.verticalLayout_52.setStretch(1, 1)
        self.verticalLayout_52.setStretch(2, 1)
        self.horizontalLayout_22.addLayout(self.verticalLayout_52)
        self.tabWidget_6.addTab(self.tab_17, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.tab_18)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.AshingAdUnlockImg = QtWidgets.QLabel(self.tab_18)
        self.AshingAdUnlockImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AshingAdUnlockImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AshingAdUnlockImg.setObjectName("AshingAdUnlockImg")
        self.verticalLayout_53.addWidget(self.AshingAdUnlockImg)
        self.label_59 = QtWidgets.QLabel(self.tab_18)
        self.label_59.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_53.addWidget(self.label_59)
        self.AshingAdUnlockPath = QtWidgets.QTextBrowser(self.tab_18)
        self.AshingAdUnlockPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingAdUnlockPath.setObjectName("AshingAdUnlockPath")
        self.verticalLayout_53.addWidget(self.AshingAdUnlockPath)
        self.AshingAdUnlockLook = QtWidgets.QPushButton(self.tab_18)
        self.AshingAdUnlockLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingAdUnlockLook.setObjectName("AshingAdUnlockLook")
        self.verticalLayout_53.addWidget(self.AshingAdUnlockLook)
        self.verticalLayout_53.setStretch(0, 8)
        self.verticalLayout_53.setStretch(2, 1)
        self.verticalLayout_53.setStretch(3, 1)
        self.horizontalLayout_23.addLayout(self.verticalLayout_53)
        self.verticalLayout_54 = QtWidgets.QVBoxLayout()
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.AshingAdChargeImg = QtWidgets.QLabel(self.tab_18)
        self.AshingAdChargeImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AshingAdChargeImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AshingAdChargeImg.setObjectName("AshingAdChargeImg")
        self.verticalLayout_54.addWidget(self.AshingAdChargeImg)
        self.label_61 = QtWidgets.QLabel(self.tab_18)
        self.label_61.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_54.addWidget(self.label_61)
        self.AshingAdChargePath = QtWidgets.QTextBrowser(self.tab_18)
        self.AshingAdChargePath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingAdChargePath.setObjectName("AshingAdChargePath")
        self.verticalLayout_54.addWidget(self.AshingAdChargePath)
        self.AshingAdChargeLook = QtWidgets.QPushButton(self.tab_18)
        self.AshingAdChargeLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingAdChargeLook.setObjectName("AshingAdChargeLook")
        self.verticalLayout_54.addWidget(self.AshingAdChargeLook)
        self.verticalLayout_54.setStretch(0, 8)
        self.verticalLayout_54.setStretch(2, 1)
        self.verticalLayout_54.setStretch(3, 1)
        self.horizontalLayout_23.addLayout(self.verticalLayout_54)
        self.verticalLayout_55 = QtWidgets.QVBoxLayout()
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.AshingAdHomeImg = QtWidgets.QLabel(self.tab_18)
        self.AshingAdHomeImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AshingAdHomeImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AshingAdHomeImg.setObjectName("AshingAdHomeImg")
        self.verticalLayout_55.addWidget(self.AshingAdHomeImg)
        self.label_63 = QtWidgets.QLabel(self.tab_18)
        self.label_63.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_55.addWidget(self.label_63)
        self.AshingAdHomePath = QtWidgets.QTextBrowser(self.tab_18)
        self.AshingAdHomePath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingAdHomePath.setObjectName("AshingAdHomePath")
        self.verticalLayout_55.addWidget(self.AshingAdHomePath)
        self.AshingAdHomeLook = QtWidgets.QPushButton(self.tab_18)
        self.AshingAdHomeLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingAdHomeLook.setObjectName("AshingAdHomeLook")
        self.verticalLayout_55.addWidget(self.AshingAdHomeLook)
        self.verticalLayout_55.setStretch(0, 8)
        self.verticalLayout_55.setStretch(2, 1)
        self.verticalLayout_55.setStretch(3, 1)
        self.horizontalLayout_23.addLayout(self.verticalLayout_55)
        self.verticalLayout_56 = QtWidgets.QVBoxLayout()
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.AshingAdWifiImg = QtWidgets.QLabel(self.tab_18)
        self.AshingAdWifiImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AshingAdWifiImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AshingAdWifiImg.setObjectName("AshingAdWifiImg")
        self.verticalLayout_56.addWidget(self.AshingAdWifiImg)
        self.label_65 = QtWidgets.QLabel(self.tab_18)
        self.label_65.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_56.addWidget(self.label_65)
        self.AshingAdWifiPath = QtWidgets.QTextBrowser(self.tab_18)
        self.AshingAdWifiPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingAdWifiPath.setObjectName("AshingAdWifiPath")
        self.verticalLayout_56.addWidget(self.AshingAdWifiPath)
        self.AshingAdWifiLook = QtWidgets.QPushButton(self.tab_18)
        self.AshingAdWifiLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingAdWifiLook.setObjectName("AshingAdWifiLook")
        self.verticalLayout_56.addWidget(self.AshingAdWifiLook)
        self.verticalLayout_56.setStretch(0, 8)
        self.verticalLayout_56.setStretch(2, 1)
        self.verticalLayout_56.setStretch(3, 1)
        self.horizontalLayout_23.addLayout(self.verticalLayout_56)
        self.verticalLayout_57 = QtWidgets.QVBoxLayout()
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.AshingAdTimerImg = QtWidgets.QLabel(self.tab_18)
        self.AshingAdTimerImg.setStyleSheet("font: 14pt \"幼圆\";\n"
"border-color: rgb(170, 255, 127);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius:10px;")
        self.AshingAdTimerImg.setAlignment(QtCore.Qt.AlignCenter)
        self.AshingAdTimerImg.setObjectName("AshingAdTimerImg")
        self.verticalLayout_57.addWidget(self.AshingAdTimerImg)
        self.label_67 = QtWidgets.QLabel(self.tab_18)
        self.label_67.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_57.addWidget(self.label_67)
        self.AshingAdTimerPath = QtWidgets.QTextBrowser(self.tab_18)
        self.AshingAdTimerPath.setStyleSheet("border-radius: 20px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.AshingAdTimerPath.setObjectName("AshingAdTimerPath")
        self.verticalLayout_57.addWidget(self.AshingAdTimerPath)
        self.AshingAdTimerLook = QtWidgets.QPushButton(self.tab_18)
        self.AshingAdTimerLook.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.AshingAdTimerLook.setObjectName("AshingAdTimerLook")
        self.verticalLayout_57.addWidget(self.AshingAdTimerLook)
        self.verticalLayout_57.setStretch(0, 8)
        self.verticalLayout_57.setStretch(2, 1)
        self.verticalLayout_57.setStretch(3, 1)
        self.horizontalLayout_23.addLayout(self.verticalLayout_57)
        self.tabWidget_6.addTab(self.tab_18, "")
        self.verticalLayout_58.addWidget(self.tabWidget_6)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.verticalLayout_3.addWidget(self.tabWidget_3)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 9)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_59 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.CreateDirText = QtWidgets.QTextEdit(self.tab_6)
        self.CreateDirText.setStyleSheet("border-radius: 20px;\n"
"font: 12pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.CreateDirText.setObjectName("CreateDirText")
        self.verticalLayout_59.addWidget(self.CreateDirText)
        self.CreateDir = QtWidgets.QPushButton(self.tab_6)
        self.CreateDir.setMinimumSize(QtCore.QSize(0, 100))
        self.CreateDir.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 28pt \"幼圆\";}")
        self.CreateDir.setObjectName("CreateDir")
        self.verticalLayout_59.addWidget(self.CreateDir)
        self.CreateClear = QtWidgets.QPushButton(self.tab_6)
        self.CreateClear.setMinimumSize(QtCore.QSize(0, 100))
        self.CreateClear.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 28pt \"幼圆\";}")
        self.CreateClear.setObjectName("CreateClear")
        self.verticalLayout_59.addWidget(self.CreateClear)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "测试工具箱-Ae"))
        self.label.setText(_translate("Form", "拖入出包文件夹生成路径（注意路径不可带中文）："))
        self.SelectOnline.setText(_translate("Form", "查询"))
        self.ClearOnlineText.setText(_translate("Form", "清空"))
        self.label_2.setText(_translate("Form", "失败"))
        self.label_3.setText(_translate("Form", "成功"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Form", "    查询在线配置    "))
        self.label_4.setText(_translate("Form", "项目ID："))
        self.label_5.setText(_translate("Form", "渠道："))
        self.SelectAd.setText(_translate("Form", "查询"))
        self.ClearAdText.setText(_translate("Form", "清空"))
        self.label_8.setText(_translate("Form", "all分组："))
        self.label_7.setText(_translate("Form", "1066A_A分组："))
        self.label_6.setText(_translate("Form", "1066B_B分组："))
        self.label_9.setText(_translate("Form", "1066C_C分组："))
        self.label_11.setText(_translate("Form", "已配置的开屏广告位："))
        self.SplashCfgText.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'幼圆\';\"><br /></p></body></html>"))
        self.label_12.setText(_translate("Form", "已配置的信息流广告位："))
        self.label_10.setText(_translate("Form", "已配置的插屏广告位："))
        self.label_13.setText(_translate("Form", "已配置的视频广告位："))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("Form", "广告位"))
        self.label_15.setText(_translate("Form", "已配置的开屏广告源："))
        self.label_16.setText(_translate("Form", "已配置的信息流广告源："))
        self.label_17.setText(_translate("Form", "已配置的插屏广告源："))
        self.label_14.setText(_translate("Form", "已配置的视频广告源："))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("Form", "广告源"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "    查询广告配置    "))
        self.label_18.setText(_translate("Form", "项目id："))
        self.label_19.setText(_translate("Form", "渠道："))
        self.label_20.setText(_translate("Form", "出包备注："))
        self.VerifyAd.setText(_translate("Form", "查询"))
        self.ClearVerifyAdText.setText(_translate("Form", "清空"))
        self.label_21.setText(_translate("Form", "匹配的广告位："))
        self.label_22.setText(_translate("Form", "缺少的广告位："))
        self.label_23.setText(_translate("Form", "冗余的广告位："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "    确认广告配置    "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "       查询       "))
        self.DevicesRefresh.setText(_translate("Form", "刷新"))
        self.label_24.setText(_translate("Form", "创建五图文件夹"))
        self.ImgMkdirName.setText(_translate("Form", "创建目录"))
        self.ImgOne.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.ScreenOne.setText(_translate("Form", "截图（1）"))
        self.ImgTwo.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.ScreenTwo.setText(_translate("Form", "截图（2）"))
        self.ImgThree.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.ScreenThree.setText(_translate("Form", "截图（3）"))
        self.ImgFour.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.ScreenFour.setText(_translate("Form", "截图（4）"))
        self.ImgFive.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.ScreenFive.setText(_translate("Form", "截图（5）"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("Form", "截图-五图"))
        self.ClearPathText.setText(_translate("Form", "清空"))
        self.label_30.setText(_translate("Form", "选择安装来源（模拟来源安装）："))
        self.DemoApp.setItemText(0, _translate("Form", "选择后点击安装按钮"))
        self.DemoApp.setItemText(1, _translate("Form", "模拟小米安装来源"))
        self.DemoApp.setItemText(2, _translate("Form", "模拟华为安装来源"))
        self.DemoApp.setItemText(3, _translate("Form", "模拟vivo安装来源"))
        self.DemoApp.setItemText(4, _translate("Form", "模拟oppo安装来源"))
        self.DemoApp.setItemText(5, _translate("Form", "debug安装（安装后同时开启debug）"))
        self.DemoApp.setItemText(6, _translate("Form", "正常安装"))
        self.InstallApp.setText(_translate("Form", "安装"))
        self.StartApp.setText(_translate("Form", "启动应用"))
        self.CheckProcess.setText(_translate("Form", "查看进程"))
        self.StopApp.setText(_translate("Form", "强停应用"))
        self.UninstallApp.setText(_translate("Form", "卸载应用"))
        self.ClearApp.setText(_translate("Form", "清除应用信息"))
        self.DebugApp.setText(_translate("Form", "开Debug"))
        self.UndebugApp.setText(_translate("Form", "关Debug"))
        self.label_31.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt;\">进</span></p><p><span style=\" font-size:28pt;\">程</span></p><p><span style=\" font-size:28pt;\">信</span></p><p><span style=\" font-size:28pt;\">息</span></p></body></html>"))
        self.ClearProcessText.setText(_translate("Form", "清空"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("Form", "测试-工具"))
        self.AutoStart.setText(_translate("Form", "启动"))
        self.AutoClearPathText.setText(_translate("Form", "清空文本"))
        self.label_32.setText(_translate("Form", "自动化信息详情："))
        self.label_33.setText(_translate("Form", "前提：已配置外广，保活已成功启动，外广延时已通过，包体为B包状态"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_13), _translate("Form", "详情输出页"))
        self.AutoLockImg.setText(_translate("Form", "<html><head/><body><p>锁屏新闻</p><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.AutoLockLook.setText(_translate("Form", "查看原图"))
        self.AutoUnlockImg.setText(_translate("Form", "<html><head/><body><p>解锁后弹窗</p><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.AutoUnlockLook.setText(_translate("Form", "查看原图"))
        self.AutoChargeImg.setText(_translate("Form", "<html><head/><body><p>插拔电弹窗</p><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.AutoChargeLook.setText(_translate("Form", "查看原图"))
        self.AutoWifiImg.setText(_translate("Form", "<html><head/><body><p>WiFi弹窗</p><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.AutoWifiLook.setText(_translate("Form", "查看原图"))
        self.AutoTimerImg.setText(_translate("Form", "<html><head/><body><p>定时弹窗</p><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.AutoTimerLook.setText(_translate("Form", "查看原图"))
        self.AutoHomeImg.setText(_translate("Form", "<html><head/><body><p>home键弹窗</p><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.AutoHomeLook.setText(_translate("Form", "查看原图"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_14), _translate("Form", "弹窗截图页"))
        self.AutoAdUnlockImg.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.label_40.setText(_translate("Form", "解锁后弹窗广告展示"))
        self.AutoAdUnlockLook.setText(_translate("Form", "查看原图"))
        self.AutoAdChargeImg.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.label_43.setText(_translate("Form", "插拔电弹窗广告展示"))
        self.AutoAdChargeLook.setText(_translate("Form", "查看原图"))
        self.AutoAdHomeImg.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.label_45.setText(_translate("Form", "home键弹窗广告展示"))
        self.AutoAdHomeLook.setText(_translate("Form", "查看原图"))
        self.AutoAdWifiImg.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.label_47.setText(_translate("Form", "wifi切换弹窗广告展示"))
        self.AutoAdWifiLook.setText(_translate("Form", "查看原图"))
        self.AutoAdTimerImg.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.label_49.setText(_translate("Form", "定时弹窗广告展示"))
        self.AutoAdTimerLook.setText(_translate("Form", "查看原图"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_15), _translate("Form", "广告截图页"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("Form", "外广-自动化（强停一次）"))
        self.AshingStart.setText(_translate("Form", "启动"))
        self.AshingClearPathText.setText(_translate("Form", "清空文本"))
        self.label_50.setText(_translate("Form", "自动化信息详情："))
        self.label_51.setText(_translate("Form", "前提：已配置外广，保活已成功启动，外广延时已通过，包体为B包状态"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_16), _translate("Form", "详情输出页"))
        self.AshingLockImg.setText(_translate("Form", "<html><head/><body><p>锁屏新闻</p><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.AshingLockLook.setText(_translate("Form", "查看原图"))
        self.AshingUnlockImg.setText(_translate("Form", "<html><head/><body><p>解锁后弹窗</p><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.AshingUnlockLook.setText(_translate("Form", "查看原图"))
        self.AshingChargeImg.setText(_translate("Form", "<html><head/><body><p>插拔电弹窗</p><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.AshingChargeLook.setText(_translate("Form", "查看原图"))
        self.AshingWifiImg.setText(_translate("Form", "<html><head/><body><p>wifi弹窗</p><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.AshingWifiLook.setText(_translate("Form", "查看原图"))
        self.AshingTimerImg.setText(_translate("Form", "<html><head/><body><p>定时弹窗</p><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.AshingTimerLook.setText(_translate("Form", "查看原图"))
        self.AshingHomeImg.setText(_translate("Form", "<html><head/><body><p>home键弹窗</p><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.AshingHomeLook.setText(_translate("Form", "查看原图"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_17), _translate("Form", "弹窗截图页"))
        self.AshingAdUnlockImg.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.label_59.setText(_translate("Form", "解锁后弹窗广告展示"))
        self.AshingAdUnlockLook.setText(_translate("Form", "查看原图"))
        self.AshingAdChargeImg.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.label_61.setText(_translate("Form", "插拔电弹窗广告展示"))
        self.AshingAdChargeLook.setText(_translate("Form", "查看原图"))
        self.AshingAdHomeImg.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.label_63.setText(_translate("Form", "home键弹窗广告展示"))
        self.AshingAdHomeLook.setText(_translate("Form", "查看原图"))
        self.AshingAdWifiImg.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.label_65.setText(_translate("Form", "wifi切换弹窗广告展示"))
        self.AshingAdWifiLook.setText(_translate("Form", "查看原图"))
        self.AshingAdTimerImg.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">图</span></p><p><span style=\" font-size:22pt;\">片</span></p><p><span style=\" font-size:22pt;\">预</span></p><p><span style=\" font-size:22pt;\">览</span></p><p><span style=\" font-size:22pt;\">区</span></p></body></html>"))
        self.label_67.setText(_translate("Form", "定时弹窗广告展示"))
        self.AshingAdTimerLook.setText(_translate("Form", "查看原图"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_18), _translate("Form", "广告截图页"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("Form", "外广-自动化（强停置灰）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "       设备       "))
        self.CreateDir.setText(_translate("Form", "创建目录"))
        self.CreateClear.setText(_translate("Form", "清空文本"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "       创建目录       "))
import ico_rc
