# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(389, 372)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pid = QtWidgets.QLineEdit(Form)
        self.pid.setObjectName("pid")
        self.horizontalLayout.addWidget(self.pid)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.chan = QtWidgets.QLineEdit(Form)
        self.chan.setObjectName("chan")
        self.horizontalLayout_2.addWidget(self.chan)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.select = QtWidgets.QPushButton(Form)
        self.select.setObjectName("select")
        self.horizontalLayout_3.addWidget(self.select)
        self.clear = QtWidgets.QPushButton(Form)
        self.clear.setObjectName("clear")
        self.horizontalLayout_3.addWidget(self.clear)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.info = QtWidgets.QTextBrowser(Form)
        self.info.setObjectName("info")
        self.verticalLayout_2.addWidget(self.info)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "项目id："))
        self.label_2.setText(_translate("Form", "渠道：  "))
        self.select.setText(_translate("Form", "查询"))
        self.clear.setText(_translate("Form", "清空"))
