# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(816, 621)
        self.path_text = QtWidgets.QLineEdit(Form)
        self.path_text.setGeometry(QtCore.QRect(10, 40, 681, 71))
        self.path_text.setStyleSheet("font: 16pt \"微软雅黑\";")
        self.path_text.setObjectName("path_text")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 581, 21))
        self.label.setStyleSheet("font: 16pt \"幼圆\";")
        self.label.setObjectName("label")
        self.path_clear = QtWidgets.QPushButton(Form)
        self.path_clear.setGeometry(QtCore.QRect(694, 40, 111, 71))
        self.path_clear.setStyleSheet("font: 24pt \"幼圆\";")
        self.path_clear.setObjectName("path_clear")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 301, 41))
        self.label_2.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.demo_app = QtWidgets.QComboBox(Form)
        self.demo_app.setGeometry(QtCore.QRect(290, 120, 281, 41))
        self.demo_app.setStyleSheet("font: 12pt \"幼圆\";")
        self.demo_app.setObjectName("demo_app")
        self.demo_app.addItem("")
        self.demo_app.addItem("")
        self.demo_app.addItem("")
        self.demo_app.addItem("")
        self.demo_app.addItem("")
        self.demo_app.addItem("")
        self.demo_app.addItem("")
        self.install = QtWidgets.QPushButton(Form)
        self.install.setGeometry(QtCore.QRect(580, 120, 71, 41))
        self.install.setStyleSheet("font: 14pt \"幼圆\";")
        self.install.setObjectName("install")
        self.start_app = QtWidgets.QPushButton(Form)
        self.start_app.setGeometry(QtCore.QRect(10, 170, 91, 41))
        self.start_app.setStyleSheet("font: 12pt \"幼圆\";")
        self.start_app.setObjectName("start_app")
        self.check_pro = QtWidgets.QPushButton(Form)
        self.check_pro.setGeometry(QtCore.QRect(110, 170, 91, 41))
        self.check_pro.setStyleSheet("font: 12pt \"幼圆\";")
        self.check_pro.setObjectName("check_pro")
        self.uninstall_app = QtWidgets.QPushButton(Form)
        self.uninstall_app.setGeometry(QtCore.QRect(310, 170, 91, 41))
        self.uninstall_app.setStyleSheet("font: 12pt \"幼圆\";")
        self.uninstall_app.setObjectName("uninstall_app")
        self.stop_app = QtWidgets.QPushButton(Form)
        self.stop_app.setGeometry(QtCore.QRect(210, 170, 91, 41))
        self.stop_app.setStyleSheet("font: 12pt \"幼圆\";")
        self.stop_app.setObjectName("stop_app")
        self.debug = QtWidgets.QPushButton(Form)
        self.debug.setGeometry(QtCore.QRect(540, 170, 91, 41))
        self.debug.setStyleSheet("font: 12pt \"幼圆\";")
        self.debug.setObjectName("debug")
        self.clear_app = QtWidgets.QPushButton(Form)
        self.clear_app.setGeometry(QtCore.QRect(410, 170, 121, 41))
        self.clear_app.setStyleSheet("font: 12pt \"幼圆\";")
        self.clear_app.setObjectName("clear_app")
        self.undebug = QtWidgets.QPushButton(Form)
        self.undebug.setGeometry(QtCore.QRect(640, 170, 91, 41))
        self.undebug.setStyleSheet("font: 12pt \"幼圆\";")
        self.undebug.setObjectName("undebug")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 31, 341))
        self.label_3.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_3.setObjectName("label_3")
        self.pro_text = QtWidgets.QTextBrowser(Form)
        self.pro_text.setGeometry(QtCore.QRect(40, 220, 671, 391))
        self.pro_text.setObjectName("pro_text")
        self.pro_clear = QtWidgets.QPushButton(Form)
        self.pro_clear.setGeometry(QtCore.QRect(720, 220, 81, 391))
        self.pro_clear.setStyleSheet("font: 14pt \"幼圆\";")
        self.pro_clear.setObjectName("pro_clear")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "拖入安装包【注意路径上不可带有中文！！！】"))
        self.path_clear.setText(_translate("Form", "清空"))
        self.label_2.setText(_translate("Form", "选择安装来源（模拟来源安装）"))
        self.demo_app.setItemText(0, _translate("Form", "选择后点击安装按钮"))
        self.demo_app.setItemText(1, _translate("Form", "模拟小米安装来源"))
        self.demo_app.setItemText(2, _translate("Form", "模拟华为安装来源"))
        self.demo_app.setItemText(3, _translate("Form", "模拟vivo安装来源"))
        self.demo_app.setItemText(4, _translate("Form", "模拟oppo安装来源"))
        self.demo_app.setItemText(5, _translate("Form", "debug安装"))
        self.demo_app.setItemText(6, _translate("Form", "正常安装"))
        self.install.setText(_translate("Form", "安装"))
        self.start_app.setText(_translate("Form", "启动应用"))
        self.check_pro.setText(_translate("Form", "查看进程"))
        self.uninstall_app.setText(_translate("Form", "卸载应用"))
        self.stop_app.setText(_translate("Form", "强停应用"))
        self.debug.setText(_translate("Form", "开debug"))
        self.clear_app.setText(_translate("Form", "清除应用信息"))
        self.undebug.setText(_translate("Form", "关debug"))
        self.label_3.setText(_translate("Form", "进\n"
"程\n"
"信\n"
"息"))
        self.pro_clear.setText(_translate("Form", "清\n"
"空"))
