# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.text = QtWidgets.QTextEdit(Form)
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.encryp = QtWidgets.QPushButton(Form)
        self.encryp.setObjectName("encryp")
        self.horizontalLayout.addWidget(self.encryp)
        self.decode = QtWidgets.QPushButton(Form)
        self.decode.setObjectName("decode")
        self.horizontalLayout.addWidget(self.decode)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.encryp_text = QtWidgets.QTextEdit(Form)
        self.encryp_text.setObjectName("encryp_text")
        self.verticalLayout.addWidget(self.encryp_text)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.encryp.setText(_translate("Form", "AES加密"))
        self.decode.setText(_translate("Form", "AES解密"))
