# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import qtawesome as qta



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(463, 300)
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(":/WindowTitle/WindowIco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(qta.icon('mdi.restart', color='green'))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.KeyName = QtWidgets.QLineEdit(Form)
        self.KeyName.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.KeyName.setObjectName("KeyName")
        self.horizontalLayout.addWidget(self.KeyName)
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("font: 10pt \"幼圆\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.KeyPassword = QtWidgets.QLineEdit(Form)
        self.KeyPassword.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.KeyPassword.setObjectName("KeyPassword")
        self.horizontalLayout.addWidget(self.KeyPassword)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setStyleSheet("font: 10pt \"幼圆\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.KeyFile = QtWidgets.QLineEdit(Form)
        self.KeyFile.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.KeyFile.setObjectName("KeyFile")
        self.horizontalLayout_2.addWidget(self.KeyFile)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.HashSelect = QtWidgets.QPushButton(Form)
        self.HashSelect.setMinimumSize(QtCore.QSize(0, 60))
        self.HashSelect.setStyleSheet("QPushButton\n"
"{border-radius:10px;\n"
"font: 14pt \"幼圆\";}")
        self.HashSelect.setObjectName("HashSelect")
        self.horizontalLayout_3.addWidget(self.HashSelect)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.KeyHashInfo = QtWidgets.QTextBrowser(Form)
        self.KeyHashInfo.setStyleSheet("border-radius: 20px;\n"
"font: 14pt \"微软雅黑\";\n"
"color: rgb(170, 255, 127);")
        self.KeyHashInfo.setObjectName("KeyHashInfo")
        self.verticalLayout_2.addWidget(self.KeyHashInfo)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "获取keyhash"))
        self.label_2.setText(_translate("Form", "别名："))
        self.label.setText(_translate("Form", "密码："))
        self.label_3.setText(_translate("Form", "签名文件路径："))
        self.HashSelect.setText(_translate("Form", "查询"))
